// Code generated by ent, DO NOT EDIT.

package inviterewardledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the inviterewardledger type in the database.
	Label = "invite_reward_ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInviterUserID holds the string denoting the inviter_user_id field in the database.
	FieldInviterUserID = "inviter_user_id"
	// FieldInviteeUserID holds the string denoting the invitee_user_id field in the database.
	FieldInviteeUserID = "invitee_user_id"
	// FieldTriggerOrderID holds the string denoting the trigger_order_id field in the database.
	FieldTriggerOrderID = "trigger_order_id"
	// FieldRewardType holds the string denoting the reward_type field in the database.
	FieldRewardType = "reward_type"
	// FieldRewardAmount holds the string denoting the reward_amount field in the database.
	FieldRewardAmount = "reward_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldConfirmedAt holds the string denoting the confirmed_at field in the database.
	FieldConfirmedAt = "confirmed_at"
	// FieldReversedAt holds the string denoting the reversed_at field in the database.
	FieldReversedAt = "reversed_at"
	// Table holds the table name of the inviterewardledger in the database.
	Table = "invite_reward_ledger"
)

// Columns holds all SQL columns for inviterewardledger fields.
var Columns = []string{
	FieldID,
	FieldInviterUserID,
	FieldInviteeUserID,
	FieldTriggerOrderID,
	FieldRewardType,
	FieldRewardAmount,
	FieldStatus,
	FieldReason,
	FieldCreatedAt,
	FieldConfirmedAt,
	FieldReversedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RewardTypeValidator is a validator for the "reward_type" field. It is called by the builders before save.
	RewardTypeValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InviteRewardLedger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInviterUserID orders the results by the inviter_user_id field.
func ByInviterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterUserID, opts...).ToFunc()
}

// ByInviteeUserID orders the results by the invitee_user_id field.
func ByInviteeUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeUserID, opts...).ToFunc()
}

// ByTriggerOrderID orders the results by the trigger_order_id field.
func ByTriggerOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerOrderID, opts...).ToFunc()
}

// ByRewardType orders the results by the reward_type field.
func ByRewardType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardType, opts...).ToFunc()
}

// ByRewardAmount orders the results by the reward_amount field.
func ByRewardAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRewardAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByConfirmedAt orders the results by the confirmed_at field.
func ByConfirmedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedAt, opts...).ToFunc()
}

// ByReversedAt orders the results by the reversed_at field.
func ByReversedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReversedAt, opts...).ToFunc()
}
