// Code generated by ent, DO NOT EDIT.

package inviterewardledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldID, id))
}

// InviterUserID applies equality check predicate on the "inviter_user_id" field. It's identical to InviterUserIDEQ.
func InviterUserID(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldInviterUserID, v))
}

// InviteeUserID applies equality check predicate on the "invitee_user_id" field. It's identical to InviteeUserIDEQ.
func InviteeUserID(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldInviteeUserID, v))
}

// TriggerOrderID applies equality check predicate on the "trigger_order_id" field. It's identical to TriggerOrderIDEQ.
func TriggerOrderID(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldTriggerOrderID, v))
}

// RewardType applies equality check predicate on the "reward_type" field. It's identical to RewardTypeEQ.
func RewardType(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldRewardType, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldRewardAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldStatus, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// ConfirmedAt applies equality check predicate on the "confirmed_at" field. It's identical to ConfirmedAtEQ.
func ConfirmedAt(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldConfirmedAt, v))
}

// ReversedAt applies equality check predicate on the "reversed_at" field. It's identical to ReversedAtEQ.
func ReversedAt(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldReversedAt, v))
}

// InviterUserIDEQ applies the EQ predicate on the "inviter_user_id" field.
func InviterUserIDEQ(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldInviterUserID, v))
}

// InviterUserIDNEQ applies the NEQ predicate on the "inviter_user_id" field.
func InviterUserIDNEQ(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldInviterUserID, v))
}

// InviterUserIDIn applies the In predicate on the "inviter_user_id" field.
func InviterUserIDIn(vs ...int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldInviterUserID, vs...))
}

// InviterUserIDNotIn applies the NotIn predicate on the "inviter_user_id" field.
func InviterUserIDNotIn(vs ...int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldInviterUserID, vs...))
}

// InviterUserIDGT applies the GT predicate on the "inviter_user_id" field.
func InviterUserIDGT(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldInviterUserID, v))
}

// InviterUserIDGTE applies the GTE predicate on the "inviter_user_id" field.
func InviterUserIDGTE(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldInviterUserID, v))
}

// InviterUserIDLT applies the LT predicate on the "inviter_user_id" field.
func InviterUserIDLT(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldInviterUserID, v))
}

// InviterUserIDLTE applies the LTE predicate on the "inviter_user_id" field.
func InviterUserIDLTE(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldInviterUserID, v))
}

// InviteeUserIDEQ applies the EQ predicate on the "invitee_user_id" field.
func InviteeUserIDEQ(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldInviteeUserID, v))
}

// InviteeUserIDNEQ applies the NEQ predicate on the "invitee_user_id" field.
func InviteeUserIDNEQ(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldInviteeUserID, v))
}

// InviteeUserIDIn applies the In predicate on the "invitee_user_id" field.
func InviteeUserIDIn(vs ...int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldInviteeUserID, vs...))
}

// InviteeUserIDNotIn applies the NotIn predicate on the "invitee_user_id" field.
func InviteeUserIDNotIn(vs ...int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldInviteeUserID, vs...))
}

// InviteeUserIDGT applies the GT predicate on the "invitee_user_id" field.
func InviteeUserIDGT(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldInviteeUserID, v))
}

// InviteeUserIDGTE applies the GTE predicate on the "invitee_user_id" field.
func InviteeUserIDGTE(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldInviteeUserID, v))
}

// InviteeUserIDLT applies the LT predicate on the "invitee_user_id" field.
func InviteeUserIDLT(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldInviteeUserID, v))
}

// InviteeUserIDLTE applies the LTE predicate on the "invitee_user_id" field.
func InviteeUserIDLTE(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldInviteeUserID, v))
}

// TriggerOrderIDEQ applies the EQ predicate on the "trigger_order_id" field.
func TriggerOrderIDEQ(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldTriggerOrderID, v))
}

// TriggerOrderIDNEQ applies the NEQ predicate on the "trigger_order_id" field.
func TriggerOrderIDNEQ(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldTriggerOrderID, v))
}

// TriggerOrderIDIn applies the In predicate on the "trigger_order_id" field.
func TriggerOrderIDIn(vs ...int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldTriggerOrderID, vs...))
}

// TriggerOrderIDNotIn applies the NotIn predicate on the "trigger_order_id" field.
func TriggerOrderIDNotIn(vs ...int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldTriggerOrderID, vs...))
}

// TriggerOrderIDGT applies the GT predicate on the "trigger_order_id" field.
func TriggerOrderIDGT(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldTriggerOrderID, v))
}

// TriggerOrderIDGTE applies the GTE predicate on the "trigger_order_id" field.
func TriggerOrderIDGTE(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldTriggerOrderID, v))
}

// TriggerOrderIDLT applies the LT predicate on the "trigger_order_id" field.
func TriggerOrderIDLT(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldTriggerOrderID, v))
}

// TriggerOrderIDLTE applies the LTE predicate on the "trigger_order_id" field.
func TriggerOrderIDLTE(v int64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldTriggerOrderID, v))
}

// RewardTypeEQ applies the EQ predicate on the "reward_type" field.
func RewardTypeEQ(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldRewardType, v))
}

// RewardTypeNEQ applies the NEQ predicate on the "reward_type" field.
func RewardTypeNEQ(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldRewardType, v))
}

// RewardTypeIn applies the In predicate on the "reward_type" field.
func RewardTypeIn(vs ...string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldRewardType, vs...))
}

// RewardTypeNotIn applies the NotIn predicate on the "reward_type" field.
func RewardTypeNotIn(vs ...string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldRewardType, vs...))
}

// RewardTypeGT applies the GT predicate on the "reward_type" field.
func RewardTypeGT(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldRewardType, v))
}

// RewardTypeGTE applies the GTE predicate on the "reward_type" field.
func RewardTypeGTE(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldRewardType, v))
}

// RewardTypeLT applies the LT predicate on the "reward_type" field.
func RewardTypeLT(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldRewardType, v))
}

// RewardTypeLTE applies the LTE predicate on the "reward_type" field.
func RewardTypeLTE(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldRewardType, v))
}

// RewardTypeContains applies the Contains predicate on the "reward_type" field.
func RewardTypeContains(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldContains(FieldRewardType, v))
}

// RewardTypeHasPrefix applies the HasPrefix predicate on the "reward_type" field.
func RewardTypeHasPrefix(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldHasPrefix(FieldRewardType, v))
}

// RewardTypeHasSuffix applies the HasSuffix predicate on the "reward_type" field.
func RewardTypeHasSuffix(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldHasSuffix(FieldRewardType, v))
}

// RewardTypeEqualFold applies the EqualFold predicate on the "reward_type" field.
func RewardTypeEqualFold(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEqualFold(FieldRewardType, v))
}

// RewardTypeContainsFold applies the ContainsFold predicate on the "reward_type" field.
func RewardTypeContainsFold(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldContainsFold(FieldRewardType, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldRewardAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldContainsFold(FieldStatus, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldContainsFold(FieldReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// ConfirmedAtEQ applies the EQ predicate on the "confirmed_at" field.
func ConfirmedAtEQ(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldConfirmedAt, v))
}

// ConfirmedAtNEQ applies the NEQ predicate on the "confirmed_at" field.
func ConfirmedAtNEQ(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldConfirmedAt, v))
}

// ConfirmedAtIn applies the In predicate on the "confirmed_at" field.
func ConfirmedAtIn(vs ...time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldConfirmedAt, vs...))
}

// ConfirmedAtNotIn applies the NotIn predicate on the "confirmed_at" field.
func ConfirmedAtNotIn(vs ...time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldConfirmedAt, vs...))
}

// ConfirmedAtGT applies the GT predicate on the "confirmed_at" field.
func ConfirmedAtGT(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldConfirmedAt, v))
}

// ConfirmedAtGTE applies the GTE predicate on the "confirmed_at" field.
func ConfirmedAtGTE(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldConfirmedAt, v))
}

// ConfirmedAtLT applies the LT predicate on the "confirmed_at" field.
func ConfirmedAtLT(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldConfirmedAt, v))
}

// ConfirmedAtLTE applies the LTE predicate on the "confirmed_at" field.
func ConfirmedAtLTE(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldConfirmedAt, v))
}

// ConfirmedAtIsNil applies the IsNil predicate on the "confirmed_at" field.
func ConfirmedAtIsNil() predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIsNull(FieldConfirmedAt))
}

// ConfirmedAtNotNil applies the NotNil predicate on the "confirmed_at" field.
func ConfirmedAtNotNil() predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotNull(FieldConfirmedAt))
}

// ReversedAtEQ applies the EQ predicate on the "reversed_at" field.
func ReversedAtEQ(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldEQ(FieldReversedAt, v))
}

// ReversedAtNEQ applies the NEQ predicate on the "reversed_at" field.
func ReversedAtNEQ(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNEQ(FieldReversedAt, v))
}

// ReversedAtIn applies the In predicate on the "reversed_at" field.
func ReversedAtIn(vs ...time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIn(FieldReversedAt, vs...))
}

// ReversedAtNotIn applies the NotIn predicate on the "reversed_at" field.
func ReversedAtNotIn(vs ...time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotIn(FieldReversedAt, vs...))
}

// ReversedAtGT applies the GT predicate on the "reversed_at" field.
func ReversedAtGT(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGT(FieldReversedAt, v))
}

// ReversedAtGTE applies the GTE predicate on the "reversed_at" field.
func ReversedAtGTE(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldGTE(FieldReversedAt, v))
}

// ReversedAtLT applies the LT predicate on the "reversed_at" field.
func ReversedAtLT(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLT(FieldReversedAt, v))
}

// ReversedAtLTE applies the LTE predicate on the "reversed_at" field.
func ReversedAtLTE(v time.Time) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldLTE(FieldReversedAt, v))
}

// ReversedAtIsNil applies the IsNil predicate on the "reversed_at" field.
func ReversedAtIsNil() predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldIsNull(FieldReversedAt))
}

// ReversedAtNotNil applies the NotNil predicate on the "reversed_at" field.
func ReversedAtNotNil() predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.FieldNotNull(FieldReversedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InviteRewardLedger) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InviteRewardLedger) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InviteRewardLedger) predicate.InviteRewardLedger {
	return predicate.InviteRewardLedger(sql.NotPredicates(p))
}
