// Code generated by ent, DO NOT EDIT.

package invoicedocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoicedocument type in the database.
	Label = "invoice_document"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInvoiceRequestID holds the string denoting the invoice_request_id field in the database.
	FieldInvoiceRequestID = "invoice_request_id"
	// FieldInvoiceNo holds the string denoting the invoice_no field in the database.
	FieldInvoiceNo = "invoice_no"
	// FieldInvoiceCode holds the string denoting the invoice_code field in the database.
	FieldInvoiceCode = "invoice_code"
	// FieldFileURL holds the string denoting the file_url field in the database.
	FieldFileURL = "file_url"
	// FieldFileType holds the string denoting the file_type field in the database.
	FieldFileType = "file_type"
	// FieldRawPayloadSummary holds the string denoting the raw_payload_summary field in the database.
	FieldRawPayloadSummary = "raw_payload_summary"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the invoicedocument in the database.
	Table = "invoice_documents"
)

// Columns holds all SQL columns for invoicedocument fields.
var Columns = []string{
	FieldID,
	FieldInvoiceRequestID,
	FieldInvoiceNo,
	FieldInvoiceCode,
	FieldFileURL,
	FieldFileType,
	FieldRawPayloadSummary,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// InvoiceNoValidator is a validator for the "invoice_no" field. It is called by the builders before save.
	InvoiceNoValidator func(string) error
	// InvoiceCodeValidator is a validator for the "invoice_code" field. It is called by the builders before save.
	InvoiceCodeValidator func(string) error
	// FileTypeValidator is a validator for the "file_type" field. It is called by the builders before save.
	FileTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceDocument queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInvoiceRequestID orders the results by the invoice_request_id field.
func ByInvoiceRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceRequestID, opts...).ToFunc()
}

// ByInvoiceNo orders the results by the invoice_no field.
func ByInvoiceNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceNo, opts...).ToFunc()
}

// ByInvoiceCode orders the results by the invoice_code field.
func ByInvoiceCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceCode, opts...).ToFunc()
}

// ByFileURL orders the results by the file_url field.
func ByFileURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileURL, opts...).ToFunc()
}

// ByFileType orders the results by the file_type field.
func ByFileType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
