// Code generated by ent, DO NOT EDIT.

package invoicedocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLTE(FieldID, id))
}

// InvoiceRequestID applies equality check predicate on the "invoice_request_id" field. It's identical to InvoiceRequestIDEQ.
func InvoiceRequestID(v int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// InvoiceNo applies equality check predicate on the "invoice_no" field. It's identical to InvoiceNoEQ.
func InvoiceNo(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceCode applies equality check predicate on the "invoice_code" field. It's identical to InvoiceCodeEQ.
func InvoiceCode(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldInvoiceCode, v))
}

// FileURL applies equality check predicate on the "file_url" field. It's identical to FileURLEQ.
func FileURL(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldFileURL, v))
}

// FileType applies equality check predicate on the "file_type" field. It's identical to FileTypeEQ.
func FileType(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldFileType, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// InvoiceRequestIDEQ applies the EQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDEQ(v int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDNEQ applies the NEQ predicate on the "invoice_request_id" field.
func InvoiceRequestIDNEQ(v int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNEQ(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDIn applies the In predicate on the "invoice_request_id" field.
func InvoiceRequestIDIn(vs ...int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDNotIn applies the NotIn predicate on the "invoice_request_id" field.
func InvoiceRequestIDNotIn(vs ...int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotIn(FieldInvoiceRequestID, vs...))
}

// InvoiceRequestIDGT applies the GT predicate on the "invoice_request_id" field.
func InvoiceRequestIDGT(v int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDGTE applies the GTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDGTE(v int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGTE(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLT applies the LT predicate on the "invoice_request_id" field.
func InvoiceRequestIDLT(v int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLT(FieldInvoiceRequestID, v))
}

// InvoiceRequestIDLTE applies the LTE predicate on the "invoice_request_id" field.
func InvoiceRequestIDLTE(v int64) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLTE(FieldInvoiceRequestID, v))
}

// InvoiceNoEQ applies the EQ predicate on the "invoice_no" field.
func InvoiceNoEQ(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceNoNEQ applies the NEQ predicate on the "invoice_no" field.
func InvoiceNoNEQ(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNEQ(FieldInvoiceNo, v))
}

// InvoiceNoIn applies the In predicate on the "invoice_no" field.
func InvoiceNoIn(vs ...string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIn(FieldInvoiceNo, vs...))
}

// InvoiceNoNotIn applies the NotIn predicate on the "invoice_no" field.
func InvoiceNoNotIn(vs ...string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotIn(FieldInvoiceNo, vs...))
}

// InvoiceNoGT applies the GT predicate on the "invoice_no" field.
func InvoiceNoGT(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGT(FieldInvoiceNo, v))
}

// InvoiceNoGTE applies the GTE predicate on the "invoice_no" field.
func InvoiceNoGTE(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGTE(FieldInvoiceNo, v))
}

// InvoiceNoLT applies the LT predicate on the "invoice_no" field.
func InvoiceNoLT(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLT(FieldInvoiceNo, v))
}

// InvoiceNoLTE applies the LTE predicate on the "invoice_no" field.
func InvoiceNoLTE(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLTE(FieldInvoiceNo, v))
}

// InvoiceNoContains applies the Contains predicate on the "invoice_no" field.
func InvoiceNoContains(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldContains(FieldInvoiceNo, v))
}

// InvoiceNoHasPrefix applies the HasPrefix predicate on the "invoice_no" field.
func InvoiceNoHasPrefix(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldHasPrefix(FieldInvoiceNo, v))
}

// InvoiceNoHasSuffix applies the HasSuffix predicate on the "invoice_no" field.
func InvoiceNoHasSuffix(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldHasSuffix(FieldInvoiceNo, v))
}

// InvoiceNoIsNil applies the IsNil predicate on the "invoice_no" field.
func InvoiceNoIsNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIsNull(FieldInvoiceNo))
}

// InvoiceNoNotNil applies the NotNil predicate on the "invoice_no" field.
func InvoiceNoNotNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotNull(FieldInvoiceNo))
}

// InvoiceNoEqualFold applies the EqualFold predicate on the "invoice_no" field.
func InvoiceNoEqualFold(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEqualFold(FieldInvoiceNo, v))
}

// InvoiceNoContainsFold applies the ContainsFold predicate on the "invoice_no" field.
func InvoiceNoContainsFold(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldContainsFold(FieldInvoiceNo, v))
}

// InvoiceCodeEQ applies the EQ predicate on the "invoice_code" field.
func InvoiceCodeEQ(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldInvoiceCode, v))
}

// InvoiceCodeNEQ applies the NEQ predicate on the "invoice_code" field.
func InvoiceCodeNEQ(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNEQ(FieldInvoiceCode, v))
}

// InvoiceCodeIn applies the In predicate on the "invoice_code" field.
func InvoiceCodeIn(vs ...string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIn(FieldInvoiceCode, vs...))
}

// InvoiceCodeNotIn applies the NotIn predicate on the "invoice_code" field.
func InvoiceCodeNotIn(vs ...string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotIn(FieldInvoiceCode, vs...))
}

// InvoiceCodeGT applies the GT predicate on the "invoice_code" field.
func InvoiceCodeGT(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGT(FieldInvoiceCode, v))
}

// InvoiceCodeGTE applies the GTE predicate on the "invoice_code" field.
func InvoiceCodeGTE(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGTE(FieldInvoiceCode, v))
}

// InvoiceCodeLT applies the LT predicate on the "invoice_code" field.
func InvoiceCodeLT(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLT(FieldInvoiceCode, v))
}

// InvoiceCodeLTE applies the LTE predicate on the "invoice_code" field.
func InvoiceCodeLTE(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLTE(FieldInvoiceCode, v))
}

// InvoiceCodeContains applies the Contains predicate on the "invoice_code" field.
func InvoiceCodeContains(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldContains(FieldInvoiceCode, v))
}

// InvoiceCodeHasPrefix applies the HasPrefix predicate on the "invoice_code" field.
func InvoiceCodeHasPrefix(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldHasPrefix(FieldInvoiceCode, v))
}

// InvoiceCodeHasSuffix applies the HasSuffix predicate on the "invoice_code" field.
func InvoiceCodeHasSuffix(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldHasSuffix(FieldInvoiceCode, v))
}

// InvoiceCodeIsNil applies the IsNil predicate on the "invoice_code" field.
func InvoiceCodeIsNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIsNull(FieldInvoiceCode))
}

// InvoiceCodeNotNil applies the NotNil predicate on the "invoice_code" field.
func InvoiceCodeNotNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotNull(FieldInvoiceCode))
}

// InvoiceCodeEqualFold applies the EqualFold predicate on the "invoice_code" field.
func InvoiceCodeEqualFold(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEqualFold(FieldInvoiceCode, v))
}

// InvoiceCodeContainsFold applies the ContainsFold predicate on the "invoice_code" field.
func InvoiceCodeContainsFold(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldContainsFold(FieldInvoiceCode, v))
}

// FileURLEQ applies the EQ predicate on the "file_url" field.
func FileURLEQ(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldFileURL, v))
}

// FileURLNEQ applies the NEQ predicate on the "file_url" field.
func FileURLNEQ(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNEQ(FieldFileURL, v))
}

// FileURLIn applies the In predicate on the "file_url" field.
func FileURLIn(vs ...string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIn(FieldFileURL, vs...))
}

// FileURLNotIn applies the NotIn predicate on the "file_url" field.
func FileURLNotIn(vs ...string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotIn(FieldFileURL, vs...))
}

// FileURLGT applies the GT predicate on the "file_url" field.
func FileURLGT(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGT(FieldFileURL, v))
}

// FileURLGTE applies the GTE predicate on the "file_url" field.
func FileURLGTE(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGTE(FieldFileURL, v))
}

// FileURLLT applies the LT predicate on the "file_url" field.
func FileURLLT(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLT(FieldFileURL, v))
}

// FileURLLTE applies the LTE predicate on the "file_url" field.
func FileURLLTE(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLTE(FieldFileURL, v))
}

// FileURLContains applies the Contains predicate on the "file_url" field.
func FileURLContains(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldContains(FieldFileURL, v))
}

// FileURLHasPrefix applies the HasPrefix predicate on the "file_url" field.
func FileURLHasPrefix(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldHasPrefix(FieldFileURL, v))
}

// FileURLHasSuffix applies the HasSuffix predicate on the "file_url" field.
func FileURLHasSuffix(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldHasSuffix(FieldFileURL, v))
}

// FileURLIsNil applies the IsNil predicate on the "file_url" field.
func FileURLIsNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIsNull(FieldFileURL))
}

// FileURLNotNil applies the NotNil predicate on the "file_url" field.
func FileURLNotNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotNull(FieldFileURL))
}

// FileURLEqualFold applies the EqualFold predicate on the "file_url" field.
func FileURLEqualFold(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEqualFold(FieldFileURL, v))
}

// FileURLContainsFold applies the ContainsFold predicate on the "file_url" field.
func FileURLContainsFold(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldContainsFold(FieldFileURL, v))
}

// FileTypeEQ applies the EQ predicate on the "file_type" field.
func FileTypeEQ(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldFileType, v))
}

// FileTypeNEQ applies the NEQ predicate on the "file_type" field.
func FileTypeNEQ(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNEQ(FieldFileType, v))
}

// FileTypeIn applies the In predicate on the "file_type" field.
func FileTypeIn(vs ...string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIn(FieldFileType, vs...))
}

// FileTypeNotIn applies the NotIn predicate on the "file_type" field.
func FileTypeNotIn(vs ...string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotIn(FieldFileType, vs...))
}

// FileTypeGT applies the GT predicate on the "file_type" field.
func FileTypeGT(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGT(FieldFileType, v))
}

// FileTypeGTE applies the GTE predicate on the "file_type" field.
func FileTypeGTE(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGTE(FieldFileType, v))
}

// FileTypeLT applies the LT predicate on the "file_type" field.
func FileTypeLT(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLT(FieldFileType, v))
}

// FileTypeLTE applies the LTE predicate on the "file_type" field.
func FileTypeLTE(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLTE(FieldFileType, v))
}

// FileTypeContains applies the Contains predicate on the "file_type" field.
func FileTypeContains(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldContains(FieldFileType, v))
}

// FileTypeHasPrefix applies the HasPrefix predicate on the "file_type" field.
func FileTypeHasPrefix(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldHasPrefix(FieldFileType, v))
}

// FileTypeHasSuffix applies the HasSuffix predicate on the "file_type" field.
func FileTypeHasSuffix(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldHasSuffix(FieldFileType, v))
}

// FileTypeIsNil applies the IsNil predicate on the "file_type" field.
func FileTypeIsNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIsNull(FieldFileType))
}

// FileTypeNotNil applies the NotNil predicate on the "file_type" field.
func FileTypeNotNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotNull(FieldFileType))
}

// FileTypeEqualFold applies the EqualFold predicate on the "file_type" field.
func FileTypeEqualFold(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEqualFold(FieldFileType, v))
}

// FileTypeContainsFold applies the ContainsFold predicate on the "file_type" field.
func FileTypeContainsFold(v string) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldContainsFold(FieldFileType, v))
}

// RawPayloadSummaryIsNil applies the IsNil predicate on the "raw_payload_summary" field.
func RawPayloadSummaryIsNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIsNull(FieldRawPayloadSummary))
}

// RawPayloadSummaryNotNil applies the NotNil predicate on the "raw_payload_summary" field.
func RawPayloadSummaryNotNil() predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotNull(FieldRawPayloadSummary))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceDocument) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceDocument) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceDocument) predicate.InvoiceDocument {
	return predicate.InvoiceDocument(sql.NotPredicates(p))
}
