// Code generated by ent, DO NOT EDIT.

package invoiceprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldTitle, v))
}

// TaxNo applies equality check predicate on the "tax_no" field. It's identical to TaxNoEQ.
func TaxNo(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldTaxNo, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldEmail, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldPhone, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldAddress, v))
}

// BankName applies equality check predicate on the "bank_name" field. It's identical to BankNameEQ.
func BankName(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldBankName, v))
}

// BankAccount applies equality check predicate on the "bank_account" field. It's identical to BankAccountEQ.
func BankAccount(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldBankAccount, v))
}

// InvoiceType applies equality check predicate on the "invoice_type" field. It's identical to InvoiceTypeEQ.
func InvoiceType(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldInvoiceType, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldIsDefault, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldUserID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldTitle, v))
}

// TaxNoEQ applies the EQ predicate on the "tax_no" field.
func TaxNoEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldTaxNo, v))
}

// TaxNoNEQ applies the NEQ predicate on the "tax_no" field.
func TaxNoNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldTaxNo, v))
}

// TaxNoIn applies the In predicate on the "tax_no" field.
func TaxNoIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldTaxNo, vs...))
}

// TaxNoNotIn applies the NotIn predicate on the "tax_no" field.
func TaxNoNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldTaxNo, vs...))
}

// TaxNoGT applies the GT predicate on the "tax_no" field.
func TaxNoGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldTaxNo, v))
}

// TaxNoGTE applies the GTE predicate on the "tax_no" field.
func TaxNoGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldTaxNo, v))
}

// TaxNoLT applies the LT predicate on the "tax_no" field.
func TaxNoLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldTaxNo, v))
}

// TaxNoLTE applies the LTE predicate on the "tax_no" field.
func TaxNoLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldTaxNo, v))
}

// TaxNoContains applies the Contains predicate on the "tax_no" field.
func TaxNoContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldTaxNo, v))
}

// TaxNoHasPrefix applies the HasPrefix predicate on the "tax_no" field.
func TaxNoHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldTaxNo, v))
}

// TaxNoHasSuffix applies the HasSuffix predicate on the "tax_no" field.
func TaxNoHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldTaxNo, v))
}

// TaxNoIsNil applies the IsNil predicate on the "tax_no" field.
func TaxNoIsNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIsNull(FieldTaxNo))
}

// TaxNoNotNil applies the NotNil predicate on the "tax_no" field.
func TaxNoNotNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotNull(FieldTaxNo))
}

// TaxNoEqualFold applies the EqualFold predicate on the "tax_no" field.
func TaxNoEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldTaxNo, v))
}

// TaxNoContainsFold applies the ContainsFold predicate on the "tax_no" field.
func TaxNoContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldTaxNo, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldEmail, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldPhone, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressIsNil applies the IsNil predicate on the "address" field.
func AddressIsNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIsNull(FieldAddress))
}

// AddressNotNil applies the NotNil predicate on the "address" field.
func AddressNotNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotNull(FieldAddress))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldAddress, v))
}

// BankNameEQ applies the EQ predicate on the "bank_name" field.
func BankNameEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldBankName, v))
}

// BankNameNEQ applies the NEQ predicate on the "bank_name" field.
func BankNameNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldBankName, v))
}

// BankNameIn applies the In predicate on the "bank_name" field.
func BankNameIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldBankName, vs...))
}

// BankNameNotIn applies the NotIn predicate on the "bank_name" field.
func BankNameNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldBankName, vs...))
}

// BankNameGT applies the GT predicate on the "bank_name" field.
func BankNameGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldBankName, v))
}

// BankNameGTE applies the GTE predicate on the "bank_name" field.
func BankNameGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldBankName, v))
}

// BankNameLT applies the LT predicate on the "bank_name" field.
func BankNameLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldBankName, v))
}

// BankNameLTE applies the LTE predicate on the "bank_name" field.
func BankNameLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldBankName, v))
}

// BankNameContains applies the Contains predicate on the "bank_name" field.
func BankNameContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldBankName, v))
}

// BankNameHasPrefix applies the HasPrefix predicate on the "bank_name" field.
func BankNameHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldBankName, v))
}

// BankNameHasSuffix applies the HasSuffix predicate on the "bank_name" field.
func BankNameHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldBankName, v))
}

// BankNameIsNil applies the IsNil predicate on the "bank_name" field.
func BankNameIsNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIsNull(FieldBankName))
}

// BankNameNotNil applies the NotNil predicate on the "bank_name" field.
func BankNameNotNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotNull(FieldBankName))
}

// BankNameEqualFold applies the EqualFold predicate on the "bank_name" field.
func BankNameEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldBankName, v))
}

// BankNameContainsFold applies the ContainsFold predicate on the "bank_name" field.
func BankNameContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldBankName, v))
}

// BankAccountEQ applies the EQ predicate on the "bank_account" field.
func BankAccountEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldBankAccount, v))
}

// BankAccountNEQ applies the NEQ predicate on the "bank_account" field.
func BankAccountNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldBankAccount, v))
}

// BankAccountIn applies the In predicate on the "bank_account" field.
func BankAccountIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldBankAccount, vs...))
}

// BankAccountNotIn applies the NotIn predicate on the "bank_account" field.
func BankAccountNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldBankAccount, vs...))
}

// BankAccountGT applies the GT predicate on the "bank_account" field.
func BankAccountGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldBankAccount, v))
}

// BankAccountGTE applies the GTE predicate on the "bank_account" field.
func BankAccountGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldBankAccount, v))
}

// BankAccountLT applies the LT predicate on the "bank_account" field.
func BankAccountLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldBankAccount, v))
}

// BankAccountLTE applies the LTE predicate on the "bank_account" field.
func BankAccountLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldBankAccount, v))
}

// BankAccountContains applies the Contains predicate on the "bank_account" field.
func BankAccountContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldBankAccount, v))
}

// BankAccountHasPrefix applies the HasPrefix predicate on the "bank_account" field.
func BankAccountHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldBankAccount, v))
}

// BankAccountHasSuffix applies the HasSuffix predicate on the "bank_account" field.
func BankAccountHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldBankAccount, v))
}

// BankAccountIsNil applies the IsNil predicate on the "bank_account" field.
func BankAccountIsNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIsNull(FieldBankAccount))
}

// BankAccountNotNil applies the NotNil predicate on the "bank_account" field.
func BankAccountNotNil() predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotNull(FieldBankAccount))
}

// BankAccountEqualFold applies the EqualFold predicate on the "bank_account" field.
func BankAccountEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldBankAccount, v))
}

// BankAccountContainsFold applies the ContainsFold predicate on the "bank_account" field.
func BankAccountContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldBankAccount, v))
}

// InvoiceTypeEQ applies the EQ predicate on the "invoice_type" field.
func InvoiceTypeEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldInvoiceType, v))
}

// InvoiceTypeNEQ applies the NEQ predicate on the "invoice_type" field.
func InvoiceTypeNEQ(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldInvoiceType, v))
}

// InvoiceTypeIn applies the In predicate on the "invoice_type" field.
func InvoiceTypeIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldInvoiceType, vs...))
}

// InvoiceTypeNotIn applies the NotIn predicate on the "invoice_type" field.
func InvoiceTypeNotIn(vs ...string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldInvoiceType, vs...))
}

// InvoiceTypeGT applies the GT predicate on the "invoice_type" field.
func InvoiceTypeGT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldInvoiceType, v))
}

// InvoiceTypeGTE applies the GTE predicate on the "invoice_type" field.
func InvoiceTypeGTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldInvoiceType, v))
}

// InvoiceTypeLT applies the LT predicate on the "invoice_type" field.
func InvoiceTypeLT(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldInvoiceType, v))
}

// InvoiceTypeLTE applies the LTE predicate on the "invoice_type" field.
func InvoiceTypeLTE(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldInvoiceType, v))
}

// InvoiceTypeContains applies the Contains predicate on the "invoice_type" field.
func InvoiceTypeContains(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContains(FieldInvoiceType, v))
}

// InvoiceTypeHasPrefix applies the HasPrefix predicate on the "invoice_type" field.
func InvoiceTypeHasPrefix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasPrefix(FieldInvoiceType, v))
}

// InvoiceTypeHasSuffix applies the HasSuffix predicate on the "invoice_type" field.
func InvoiceTypeHasSuffix(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldHasSuffix(FieldInvoiceType, v))
}

// InvoiceTypeEqualFold applies the EqualFold predicate on the "invoice_type" field.
func InvoiceTypeEqualFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEqualFold(FieldInvoiceType, v))
}

// InvoiceTypeContainsFold applies the ContainsFold predicate on the "invoice_type" field.
func InvoiceTypeContainsFold(v string) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldContainsFold(FieldInvoiceType, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldIsDefault, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceProfile) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceProfile) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceProfile) predicate.InvoiceProfile {
	return predicate.InvoiceProfile(sql.NotPredicates(p))
}
