// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invitelink"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InviteLinkUpdate is the builder for updating InviteLink entities.
type InviteLinkUpdate struct {
	config
	hooks    []Hook
	mutation *InviteLinkMutation
}

// Where appends a list predicates to the InviteLinkUpdate builder.
func (_u *InviteLinkUpdate) Where(ps ...predicate.InviteLink) *InviteLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *InviteLinkUpdate) SetCode(v string) *InviteLinkUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InviteLinkUpdate) SetNillableCode(v *string) *InviteLinkUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *InviteLinkUpdate) SetCreatedByUserID(v int64) *InviteLinkUpdate {
	_u.mutation.ResetCreatedByUserID()
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *InviteLinkUpdate) SetNillableCreatedByUserID(v *int64) *InviteLinkUpdate {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// AddCreatedByUserID adds value to the "created_by_user_id" field.
func (_u *InviteLinkUpdate) AddCreatedByUserID(v int64) *InviteLinkUpdate {
	_u.mutation.AddCreatedByUserID(v)
	return _u
}

// SetCreatorRole sets the "creator_role" field.
func (_u *InviteLinkUpdate) SetCreatorRole(v string) *InviteLinkUpdate {
	_u.mutation.SetCreatorRole(v)
	return _u
}

// SetNillableCreatorRole sets the "creator_role" field if the given value is not nil.
func (_u *InviteLinkUpdate) SetNillableCreatorRole(v *string) *InviteLinkUpdate {
	if v != nil {
		_u.SetCreatorRole(*v)
	}
	return _u
}

// SetOwnerSalesID sets the "owner_sales_id" field.
func (_u *InviteLinkUpdate) SetOwnerSalesID(v int64) *InviteLinkUpdate {
	_u.mutation.ResetOwnerSalesID()
	_u.mutation.SetOwnerSalesID(v)
	return _u
}

// SetNillableOwnerSalesID sets the "owner_sales_id" field if the given value is not nil.
func (_u *InviteLinkUpdate) SetNillableOwnerSalesID(v *int64) *InviteLinkUpdate {
	if v != nil {
		_u.SetOwnerSalesID(*v)
	}
	return _u
}

// AddOwnerSalesID adds value to the "owner_sales_id" field.
func (_u *InviteLinkUpdate) AddOwnerSalesID(v int64) *InviteLinkUpdate {
	_u.mutation.AddOwnerSalesID(v)
	return _u
}

// ClearOwnerSalesID clears the value of the "owner_sales_id" field.
func (_u *InviteLinkUpdate) ClearOwnerSalesID() *InviteLinkUpdate {
	_u.mutation.ClearOwnerSalesID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InviteLinkUpdate) SetStatus(v string) *InviteLinkUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InviteLinkUpdate) SetNillableStatus(v *string) *InviteLinkUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *InviteLinkUpdate) SetNotes(v string) *InviteLinkUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *InviteLinkUpdate) SetNillableNotes(v *string) *InviteLinkUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *InviteLinkUpdate) ClearNotes() *InviteLinkUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InviteLinkUpdate) SetUpdatedAt(v time.Time) *InviteLinkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InviteLinkMutation object of the builder.
func (_u *InviteLinkUpdate) Mutation() *InviteLinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InviteLinkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InviteLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InviteLinkUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invitelink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteLinkUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invitelink.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InviteLink.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorRole(); ok {
		if err := invitelink.CreatorRoleValidator(v); err != nil {
			return &ValidationError{Name: "creator_role", err: fmt.Errorf(`ent: validator failed for field "InviteLink.creator_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invitelink.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InviteLink.status": %w`, err)}
		}
	}
	return nil
}

func (_u *InviteLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitelink.Table, invitelink.Columns, sqlgraph.NewFieldSpec(invitelink.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invitelink.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedByUserID(); ok {
		_spec.SetField(invitelink.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByUserID(); ok {
		_spec.AddField(invitelink.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatorRole(); ok {
		_spec.SetField(invitelink.FieldCreatorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerSalesID(); ok {
		_spec.SetField(invitelink.FieldOwnerSalesID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerSalesID(); ok {
		_spec.AddField(invitelink.FieldOwnerSalesID, field.TypeInt64, value)
	}
	if _u.mutation.OwnerSalesIDCleared() {
		_spec.ClearField(invitelink.FieldOwnerSalesID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invitelink.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(invitelink.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(invitelink.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitelink.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InviteLinkUpdateOne is the builder for updating a single InviteLink entity.
type InviteLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteLinkMutation
}

// SetCode sets the "code" field.
func (_u *InviteLinkUpdateOne) SetCode(v string) *InviteLinkUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *InviteLinkUpdateOne) SetNillableCode(v *string) *InviteLinkUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetCreatedByUserID sets the "created_by_user_id" field.
func (_u *InviteLinkUpdateOne) SetCreatedByUserID(v int64) *InviteLinkUpdateOne {
	_u.mutation.ResetCreatedByUserID()
	_u.mutation.SetCreatedByUserID(v)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user_id" field if the given value is not nil.
func (_u *InviteLinkUpdateOne) SetNillableCreatedByUserID(v *int64) *InviteLinkUpdateOne {
	if v != nil {
		_u.SetCreatedByUserID(*v)
	}
	return _u
}

// AddCreatedByUserID adds value to the "created_by_user_id" field.
func (_u *InviteLinkUpdateOne) AddCreatedByUserID(v int64) *InviteLinkUpdateOne {
	_u.mutation.AddCreatedByUserID(v)
	return _u
}

// SetCreatorRole sets the "creator_role" field.
func (_u *InviteLinkUpdateOne) SetCreatorRole(v string) *InviteLinkUpdateOne {
	_u.mutation.SetCreatorRole(v)
	return _u
}

// SetNillableCreatorRole sets the "creator_role" field if the given value is not nil.
func (_u *InviteLinkUpdateOne) SetNillableCreatorRole(v *string) *InviteLinkUpdateOne {
	if v != nil {
		_u.SetCreatorRole(*v)
	}
	return _u
}

// SetOwnerSalesID sets the "owner_sales_id" field.
func (_u *InviteLinkUpdateOne) SetOwnerSalesID(v int64) *InviteLinkUpdateOne {
	_u.mutation.ResetOwnerSalesID()
	_u.mutation.SetOwnerSalesID(v)
	return _u
}

// SetNillableOwnerSalesID sets the "owner_sales_id" field if the given value is not nil.
func (_u *InviteLinkUpdateOne) SetNillableOwnerSalesID(v *int64) *InviteLinkUpdateOne {
	if v != nil {
		_u.SetOwnerSalesID(*v)
	}
	return _u
}

// AddOwnerSalesID adds value to the "owner_sales_id" field.
func (_u *InviteLinkUpdateOne) AddOwnerSalesID(v int64) *InviteLinkUpdateOne {
	_u.mutation.AddOwnerSalesID(v)
	return _u
}

// ClearOwnerSalesID clears the value of the "owner_sales_id" field.
func (_u *InviteLinkUpdateOne) ClearOwnerSalesID() *InviteLinkUpdateOne {
	_u.mutation.ClearOwnerSalesID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InviteLinkUpdateOne) SetStatus(v string) *InviteLinkUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InviteLinkUpdateOne) SetNillableStatus(v *string) *InviteLinkUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *InviteLinkUpdateOne) SetNotes(v string) *InviteLinkUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *InviteLinkUpdateOne) SetNillableNotes(v *string) *InviteLinkUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *InviteLinkUpdateOne) ClearNotes() *InviteLinkUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InviteLinkUpdateOne) SetUpdatedAt(v time.Time) *InviteLinkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InviteLinkMutation object of the builder.
func (_u *InviteLinkUpdateOne) Mutation() *InviteLinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the InviteLinkUpdate builder.
func (_u *InviteLinkUpdateOne) Where(ps ...predicate.InviteLink) *InviteLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InviteLinkUpdateOne) Select(field string, fields ...string) *InviteLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InviteLink entity.
func (_u *InviteLinkUpdateOne) Save(ctx context.Context) (*InviteLink, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InviteLinkUpdateOne) SaveX(ctx context.Context) *InviteLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InviteLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InviteLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InviteLinkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invitelink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InviteLinkUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := invitelink.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "InviteLink.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorRole(); ok {
		if err := invitelink.CreatorRoleValidator(v); err != nil {
			return &ValidationError{Name: "creator_role", err: fmt.Errorf(`ent: validator failed for field "InviteLink.creator_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invitelink.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InviteLink.status": %w`, err)}
		}
	}
	return nil
}

func (_u *InviteLinkUpdateOne) sqlSave(ctx context.Context) (_node *InviteLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitelink.Table, invitelink.Columns, sqlgraph.NewFieldSpec(invitelink.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InviteLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitelink.FieldID)
		for _, f := range fields {
			if !invitelink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitelink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(invitelink.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedByUserID(); ok {
		_spec.SetField(invitelink.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByUserID(); ok {
		_spec.AddField(invitelink.FieldCreatedByUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatorRole(); ok {
		_spec.SetField(invitelink.FieldCreatorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerSalesID(); ok {
		_spec.SetField(invitelink.FieldOwnerSalesID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOwnerSalesID(); ok {
		_spec.AddField(invitelink.FieldOwnerSalesID, field.TypeInt64, value)
	}
	if _u.mutation.OwnerSalesIDCleared() {
		_spec.ClearField(invitelink.FieldOwnerSalesID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invitelink.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(invitelink.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(invitelink.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invitelink.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &InviteLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
