// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/inviterewardledger"
)

// InviteRewardLedger is the model entity for the InviteRewardLedger schema.
type InviteRewardLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InviterUserID holds the value of the "inviter_user_id" field.
	InviterUserID int64 `json:"inviter_user_id,omitempty"`
	// InviteeUserID holds the value of the "invitee_user_id" field.
	InviteeUserID int64 `json:"invitee_user_id,omitempty"`
	// TriggerOrderID holds the value of the "trigger_order_id" field.
	TriggerOrderID int64 `json:"trigger_order_id,omitempty"`
	// RewardType holds the value of the "reward_type" field.
	RewardType string `json:"reward_type,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ConfirmedAt holds the value of the "confirmed_at" field.
	ConfirmedAt *time.Time `json:"confirmed_at,omitempty"`
	// ReversedAt holds the value of the "reversed_at" field.
	ReversedAt   *time.Time `json:"reversed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InviteRewardLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inviterewardledger.FieldRewardAmount:
			values[i] = new(sql.NullFloat64)
		case inviterewardledger.FieldID, inviterewardledger.FieldInviterUserID, inviterewardledger.FieldInviteeUserID, inviterewardledger.FieldTriggerOrderID:
			values[i] = new(sql.NullInt64)
		case inviterewardledger.FieldRewardType, inviterewardledger.FieldStatus, inviterewardledger.FieldReason:
			values[i] = new(sql.NullString)
		case inviterewardledger.FieldCreatedAt, inviterewardledger.FieldConfirmedAt, inviterewardledger.FieldReversedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InviteRewardLedger fields.
func (_m *InviteRewardLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inviterewardledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case inviterewardledger.FieldInviterUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_user_id", values[i])
			} else if value.Valid {
				_m.InviterUserID = value.Int64
			}
		case inviterewardledger.FieldInviteeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_user_id", values[i])
			} else if value.Valid {
				_m.InviteeUserID = value.Int64
			}
		case inviterewardledger.FieldTriggerOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_order_id", values[i])
			} else if value.Valid {
				_m.TriggerOrderID = value.Int64
			}
		case inviterewardledger.FieldRewardType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reward_type", values[i])
			} else if value.Valid {
				_m.RewardType = value.String
			}
		case inviterewardledger.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case inviterewardledger.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case inviterewardledger.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case inviterewardledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case inviterewardledger.FieldConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_at", values[i])
			} else if value.Valid {
				_m.ConfirmedAt = new(time.Time)
				*_m.ConfirmedAt = value.Time
			}
		case inviterewardledger.FieldReversedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reversed_at", values[i])
			} else if value.Valid {
				_m.ReversedAt = new(time.Time)
				*_m.ReversedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InviteRewardLedger.
// This includes values selected through modifiers, order, etc.
func (_m *InviteRewardLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InviteRewardLedger.
// Note that you need to call InviteRewardLedger.Unwrap() before calling this method if this InviteRewardLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InviteRewardLedger) Update() *InviteRewardLedgerUpdateOne {
	return NewInviteRewardLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InviteRewardLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InviteRewardLedger) Unwrap() *InviteRewardLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InviteRewardLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InviteRewardLedger) String() string {
	var builder strings.Builder
	builder.WriteString("InviteRewardLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("inviter_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterUserID))
	builder.WriteString(", ")
	builder.WriteString("invitee_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeUserID))
	builder.WriteString(", ")
	builder.WriteString("trigger_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerOrderID))
	builder.WriteString(", ")
	builder.WriteString("reward_type=")
	builder.WriteString(_m.RewardType)
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConfirmedAt; v != nil {
		builder.WriteString("confirmed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReversedAt; v != nil {
		builder.WriteString("reversed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// InviteRewardLedgers is a parsable slice of InviteRewardLedger.
type InviteRewardLedgers []*InviteRewardLedger
