// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/inviterewardledger"
)

// InviteRewardLedgerCreate is the builder for creating a InviteRewardLedger entity.
type InviteRewardLedgerCreate struct {
	config
	mutation *InviteRewardLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_c *InviteRewardLedgerCreate) SetInviterUserID(v int64) *InviteRewardLedgerCreate {
	_c.mutation.SetInviterUserID(v)
	return _c
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_c *InviteRewardLedgerCreate) SetInviteeUserID(v int64) *InviteRewardLedgerCreate {
	_c.mutation.SetInviteeUserID(v)
	return _c
}

// SetTriggerOrderID sets the "trigger_order_id" field.
func (_c *InviteRewardLedgerCreate) SetTriggerOrderID(v int64) *InviteRewardLedgerCreate {
	_c.mutation.SetTriggerOrderID(v)
	return _c
}

// SetRewardType sets the "reward_type" field.
func (_c *InviteRewardLedgerCreate) SetRewardType(v string) *InviteRewardLedgerCreate {
	_c.mutation.SetRewardType(v)
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *InviteRewardLedgerCreate) SetRewardAmount(v float64) *InviteRewardLedgerCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InviteRewardLedgerCreate) SetStatus(v string) *InviteRewardLedgerCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *InviteRewardLedgerCreate) SetReason(v string) *InviteRewardLedgerCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *InviteRewardLedgerCreate) SetNillableReason(v *string) *InviteRewardLedgerCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InviteRewardLedgerCreate) SetCreatedAt(v time.Time) *InviteRewardLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InviteRewardLedgerCreate) SetNillableCreatedAt(v *time.Time) *InviteRewardLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_c *InviteRewardLedgerCreate) SetConfirmedAt(v time.Time) *InviteRewardLedgerCreate {
	_c.mutation.SetConfirmedAt(v)
	return _c
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_c *InviteRewardLedgerCreate) SetNillableConfirmedAt(v *time.Time) *InviteRewardLedgerCreate {
	if v != nil {
		_c.SetConfirmedAt(*v)
	}
	return _c
}

// SetReversedAt sets the "reversed_at" field.
func (_c *InviteRewardLedgerCreate) SetReversedAt(v time.Time) *InviteRewardLedgerCreate {
	_c.mutation.SetReversedAt(v)
	return _c
}

// SetNillableReversedAt sets the "reversed_at" field if the given value is not nil.
func (_c *InviteRewardLedgerCreate) SetNillableReversedAt(v *time.Time) *InviteRewardLedgerCreate {
	if v != nil {
		_c.SetReversedAt(*v)
	}
	return _c
}

// Mutation returns the InviteRewardLedgerMutation object of the builder.
func (_c *InviteRewardLedgerCreate) Mutation() *InviteRewardLedgerMutation {
	return _c.mutation
}

// Save creates the InviteRewardLedger in the database.
func (_c *InviteRewardLedgerCreate) Save(ctx context.Context) (*InviteRewardLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InviteRewardLedgerCreate) SaveX(ctx context.Context) *InviteRewardLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteRewardLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteRewardLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InviteRewardLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := inviterewardledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InviteRewardLedgerCreate) check() error {
	if _, ok := _c.mutation.InviterUserID(); !ok {
		return &ValidationError{Name: "inviter_user_id", err: errors.New(`ent: missing required field "InviteRewardLedger.inviter_user_id"`)}
	}
	if _, ok := _c.mutation.InviteeUserID(); !ok {
		return &ValidationError{Name: "invitee_user_id", err: errors.New(`ent: missing required field "InviteRewardLedger.invitee_user_id"`)}
	}
	if _, ok := _c.mutation.TriggerOrderID(); !ok {
		return &ValidationError{Name: "trigger_order_id", err: errors.New(`ent: missing required field "InviteRewardLedger.trigger_order_id"`)}
	}
	if _, ok := _c.mutation.RewardType(); !ok {
		return &ValidationError{Name: "reward_type", err: errors.New(`ent: missing required field "InviteRewardLedger.reward_type"`)}
	}
	if v, ok := _c.mutation.RewardType(); ok {
		if err := inviterewardledger.RewardTypeValidator(v); err != nil {
			return &ValidationError{Name: "reward_type", err: fmt.Errorf(`ent: validator failed for field "InviteRewardLedger.reward_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "InviteRewardLedger.reward_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InviteRewardLedger.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := inviterewardledger.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InviteRewardLedger.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InviteRewardLedger.created_at"`)}
	}
	return nil
}

func (_c *InviteRewardLedgerCreate) sqlSave(ctx context.Context) (*InviteRewardLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InviteRewardLedgerCreate) createSpec() (*InviteRewardLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &InviteRewardLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inviterewardledger.Table, sqlgraph.NewFieldSpec(inviterewardledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InviterUserID(); ok {
		_spec.SetField(inviterewardledger.FieldInviterUserID, field.TypeInt64, value)
		_node.InviterUserID = value
	}
	if value, ok := _c.mutation.InviteeUserID(); ok {
		_spec.SetField(inviterewardledger.FieldInviteeUserID, field.TypeInt64, value)
		_node.InviteeUserID = value
	}
	if value, ok := _c.mutation.TriggerOrderID(); ok {
		_spec.SetField(inviterewardledger.FieldTriggerOrderID, field.TypeInt64, value)
		_node.TriggerOrderID = value
	}
	if value, ok := _c.mutation.RewardType(); ok {
		_spec.SetField(inviterewardledger.FieldRewardType, field.TypeString, value)
		_node.RewardType = value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(inviterewardledger.FieldRewardAmount, field.TypeFloat64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(inviterewardledger.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(inviterewardledger.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(inviterewardledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ConfirmedAt(); ok {
		_spec.SetField(inviterewardledger.FieldConfirmedAt, field.TypeTime, value)
		_node.ConfirmedAt = &value
	}
	if value, ok := _c.mutation.ReversedAt(); ok {
		_spec.SetField(inviterewardledger.FieldReversedAt, field.TypeTime, value)
		_node.ReversedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteRewardLedger.Create().
//		SetInviterUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteRewardLedgerUpsert) {
//			SetInviterUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteRewardLedgerCreate) OnConflict(opts ...sql.ConflictOption) *InviteRewardLedgerUpsertOne {
	_c.conflict = opts
	return &InviteRewardLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteRewardLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteRewardLedgerCreate) OnConflictColumns(columns ...string) *InviteRewardLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteRewardLedgerUpsertOne{
		create: _c,
	}
}

type (
	// InviteRewardLedgerUpsertOne is the builder for "upsert"-ing
	//  one InviteRewardLedger node.
	InviteRewardLedgerUpsertOne struct {
		create *InviteRewardLedgerCreate
	}

	// InviteRewardLedgerUpsert is the "OnConflict" setter.
	InviteRewardLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviterUserID sets the "inviter_user_id" field.
func (u *InviteRewardLedgerUpsert) SetInviterUserID(v int64) *InviteRewardLedgerUpsert {
	u.Set(inviterewardledger.FieldInviterUserID, v)
	return u
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsert) UpdateInviterUserID() *InviteRewardLedgerUpsert {
	u.SetExcluded(inviterewardledger.FieldInviterUserID)
	return u
}

// AddInviterUserID adds v to the "inviter_user_id" field.
func (u *InviteRewardLedgerUpsert) AddInviterUserID(v int64) *InviteRewardLedgerUpsert {
	u.Add(inviterewardledger.FieldInviterUserID, v)
	return u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *InviteRewardLedgerUpsert) SetInviteeUserID(v int64) *InviteRewardLedgerUpsert {
	u.Set(inviterewardledger.FieldInviteeUserID, v)
	return u
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsert) UpdateInviteeUserID() *InviteRewardLedgerUpsert {
	u.SetExcluded(inviterewardledger.FieldInviteeUserID)
	return u
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *InviteRewardLedgerUpsert) AddInviteeUserID(v int64) *InviteRewardLedgerUpsert {
	u.Add(inviterewardledger.FieldInviteeUserID, v)
	return u
}

// SetTriggerOrderID sets the "trigger_order_id" field.
func (u *InviteRewardLedgerUpsert) SetTriggerOrderID(v int64) *InviteRewardLedgerUpsert {
	u.Set(inviterewardledger.FieldTriggerOrderID, v)
	return u
}

// UpdateTriggerOrderID sets the "trigger_order_id" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsert) UpdateTriggerOrderID() *InviteRewardLedgerUpsert {
	u.SetExcluded(inviterewardledger.FieldTriggerOrderID)
	return u
}

// AddTriggerOrderID adds v to the "trigger_order_id" field.
func (u *InviteRewardLedgerUpsert) AddTriggerOrderID(v int64) *InviteRewardLedgerUpsert {
	u.Add(inviterewardledger.FieldTriggerOrderID, v)
	return u
}

// SetRewardType sets the "reward_type" field.
func (u *InviteRewardLedgerUpsert) SetRewardType(v string) *InviteRewardLedgerUpsert {
	u.Set(inviterewardledger.FieldRewardType, v)
	return u
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsert) UpdateRewardType() *InviteRewardLedgerUpsert {
	u.SetExcluded(inviterewardledger.FieldRewardType)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *InviteRewardLedgerUpsert) SetRewardAmount(v float64) *InviteRewardLedgerUpsert {
	u.Set(inviterewardledger.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsert) UpdateRewardAmount() *InviteRewardLedgerUpsert {
	u.SetExcluded(inviterewardledger.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *InviteRewardLedgerUpsert) AddRewardAmount(v float64) *InviteRewardLedgerUpsert {
	u.Add(inviterewardledger.FieldRewardAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *InviteRewardLedgerUpsert) SetStatus(v string) *InviteRewardLedgerUpsert {
	u.Set(inviterewardledger.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsert) UpdateStatus() *InviteRewardLedgerUpsert {
	u.SetExcluded(inviterewardledger.FieldStatus)
	return u
}

// SetReason sets the "reason" field.
func (u *InviteRewardLedgerUpsert) SetReason(v string) *InviteRewardLedgerUpsert {
	u.Set(inviterewardledger.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsert) UpdateReason() *InviteRewardLedgerUpsert {
	u.SetExcluded(inviterewardledger.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *InviteRewardLedgerUpsert) ClearReason() *InviteRewardLedgerUpsert {
	u.SetNull(inviterewardledger.FieldReason)
	return u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *InviteRewardLedgerUpsert) SetConfirmedAt(v time.Time) *InviteRewardLedgerUpsert {
	u.Set(inviterewardledger.FieldConfirmedAt, v)
	return u
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsert) UpdateConfirmedAt() *InviteRewardLedgerUpsert {
	u.SetExcluded(inviterewardledger.FieldConfirmedAt)
	return u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *InviteRewardLedgerUpsert) ClearConfirmedAt() *InviteRewardLedgerUpsert {
	u.SetNull(inviterewardledger.FieldConfirmedAt)
	return u
}

// SetReversedAt sets the "reversed_at" field.
func (u *InviteRewardLedgerUpsert) SetReversedAt(v time.Time) *InviteRewardLedgerUpsert {
	u.Set(inviterewardledger.FieldReversedAt, v)
	return u
}

// UpdateReversedAt sets the "reversed_at" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsert) UpdateReversedAt() *InviteRewardLedgerUpsert {
	u.SetExcluded(inviterewardledger.FieldReversedAt)
	return u
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (u *InviteRewardLedgerUpsert) ClearReversedAt() *InviteRewardLedgerUpsert {
	u.SetNull(inviterewardledger.FieldReversedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InviteRewardLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteRewardLedgerUpsertOne) UpdateNewValues() *InviteRewardLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(inviterewardledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteRewardLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InviteRewardLedgerUpsertOne) Ignore() *InviteRewardLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteRewardLedgerUpsertOne) DoNothing() *InviteRewardLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteRewardLedgerCreate.OnConflict
// documentation for more info.
func (u *InviteRewardLedgerUpsertOne) Update(set func(*InviteRewardLedgerUpsert)) *InviteRewardLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteRewardLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *InviteRewardLedgerUpsertOne) SetInviterUserID(v int64) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetInviterUserID(v)
	})
}

// AddInviterUserID adds v to the "inviter_user_id" field.
func (u *InviteRewardLedgerUpsertOne) AddInviterUserID(v int64) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.AddInviterUserID(v)
	})
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertOne) UpdateInviterUserID() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateInviterUserID()
	})
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *InviteRewardLedgerUpsertOne) SetInviteeUserID(v int64) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetInviteeUserID(v)
	})
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *InviteRewardLedgerUpsertOne) AddInviteeUserID(v int64) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.AddInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertOne) UpdateInviteeUserID() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetTriggerOrderID sets the "trigger_order_id" field.
func (u *InviteRewardLedgerUpsertOne) SetTriggerOrderID(v int64) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetTriggerOrderID(v)
	})
}

// AddTriggerOrderID adds v to the "trigger_order_id" field.
func (u *InviteRewardLedgerUpsertOne) AddTriggerOrderID(v int64) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.AddTriggerOrderID(v)
	})
}

// UpdateTriggerOrderID sets the "trigger_order_id" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertOne) UpdateTriggerOrderID() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateTriggerOrderID()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *InviteRewardLedgerUpsertOne) SetRewardType(v string) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertOne) UpdateRewardType() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateRewardType()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *InviteRewardLedgerUpsertOne) SetRewardAmount(v float64) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *InviteRewardLedgerUpsertOne) AddRewardAmount(v float64) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertOne) UpdateRewardAmount() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InviteRewardLedgerUpsertOne) SetStatus(v string) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertOne) UpdateStatus() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *InviteRewardLedgerUpsertOne) SetReason(v string) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertOne) UpdateReason() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *InviteRewardLedgerUpsertOne) ClearReason() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.ClearReason()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *InviteRewardLedgerUpsertOne) SetConfirmedAt(v time.Time) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertOne) UpdateConfirmedAt() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *InviteRewardLedgerUpsertOne) ClearConfirmedAt() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.ClearConfirmedAt()
	})
}

// SetReversedAt sets the "reversed_at" field.
func (u *InviteRewardLedgerUpsertOne) SetReversedAt(v time.Time) *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetReversedAt(v)
	})
}

// UpdateReversedAt sets the "reversed_at" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertOne) UpdateReversedAt() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateReversedAt()
	})
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (u *InviteRewardLedgerUpsertOne) ClearReversedAt() *InviteRewardLedgerUpsertOne {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.ClearReversedAt()
	})
}

// Exec executes the query.
func (u *InviteRewardLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteRewardLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteRewardLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InviteRewardLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InviteRewardLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InviteRewardLedgerCreateBulk is the builder for creating many InviteRewardLedger entities in bulk.
type InviteRewardLedgerCreateBulk struct {
	config
	err      error
	builders []*InviteRewardLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the InviteRewardLedger entities in the database.
func (_c *InviteRewardLedgerCreateBulk) Save(ctx context.Context) ([]*InviteRewardLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InviteRewardLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteRewardLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InviteRewardLedgerCreateBulk) SaveX(ctx context.Context) []*InviteRewardLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InviteRewardLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InviteRewardLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InviteRewardLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteRewardLedgerUpsert) {
//			SetInviterUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InviteRewardLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *InviteRewardLedgerUpsertBulk {
	_c.conflict = opts
	return &InviteRewardLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InviteRewardLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InviteRewardLedgerCreateBulk) OnConflictColumns(columns ...string) *InviteRewardLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InviteRewardLedgerUpsertBulk{
		create: _c,
	}
}

// InviteRewardLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of InviteRewardLedger nodes.
type InviteRewardLedgerUpsertBulk struct {
	create *InviteRewardLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InviteRewardLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteRewardLedgerUpsertBulk) UpdateNewValues() *InviteRewardLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(inviterewardledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InviteRewardLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InviteRewardLedgerUpsertBulk) Ignore() *InviteRewardLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteRewardLedgerUpsertBulk) DoNothing() *InviteRewardLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteRewardLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *InviteRewardLedgerUpsertBulk) Update(set func(*InviteRewardLedgerUpsert)) *InviteRewardLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteRewardLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *InviteRewardLedgerUpsertBulk) SetInviterUserID(v int64) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetInviterUserID(v)
	})
}

// AddInviterUserID adds v to the "inviter_user_id" field.
func (u *InviteRewardLedgerUpsertBulk) AddInviterUserID(v int64) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.AddInviterUserID(v)
	})
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertBulk) UpdateInviterUserID() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateInviterUserID()
	})
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *InviteRewardLedgerUpsertBulk) SetInviteeUserID(v int64) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetInviteeUserID(v)
	})
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *InviteRewardLedgerUpsertBulk) AddInviteeUserID(v int64) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.AddInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertBulk) UpdateInviteeUserID() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetTriggerOrderID sets the "trigger_order_id" field.
func (u *InviteRewardLedgerUpsertBulk) SetTriggerOrderID(v int64) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetTriggerOrderID(v)
	})
}

// AddTriggerOrderID adds v to the "trigger_order_id" field.
func (u *InviteRewardLedgerUpsertBulk) AddTriggerOrderID(v int64) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.AddTriggerOrderID(v)
	})
}

// UpdateTriggerOrderID sets the "trigger_order_id" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertBulk) UpdateTriggerOrderID() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateTriggerOrderID()
	})
}

// SetRewardType sets the "reward_type" field.
func (u *InviteRewardLedgerUpsertBulk) SetRewardType(v string) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetRewardType(v)
	})
}

// UpdateRewardType sets the "reward_type" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertBulk) UpdateRewardType() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateRewardType()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *InviteRewardLedgerUpsertBulk) SetRewardAmount(v float64) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *InviteRewardLedgerUpsertBulk) AddRewardAmount(v float64) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertBulk) UpdateRewardAmount() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateRewardAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InviteRewardLedgerUpsertBulk) SetStatus(v string) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertBulk) UpdateStatus() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateStatus()
	})
}

// SetReason sets the "reason" field.
func (u *InviteRewardLedgerUpsertBulk) SetReason(v string) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertBulk) UpdateReason() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *InviteRewardLedgerUpsertBulk) ClearReason() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.ClearReason()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *InviteRewardLedgerUpsertBulk) SetConfirmedAt(v time.Time) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertBulk) UpdateConfirmedAt() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *InviteRewardLedgerUpsertBulk) ClearConfirmedAt() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.ClearConfirmedAt()
	})
}

// SetReversedAt sets the "reversed_at" field.
func (u *InviteRewardLedgerUpsertBulk) SetReversedAt(v time.Time) *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.SetReversedAt(v)
	})
}

// UpdateReversedAt sets the "reversed_at" field to the value that was provided on create.
func (u *InviteRewardLedgerUpsertBulk) UpdateReversedAt() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.UpdateReversedAt()
	})
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (u *InviteRewardLedgerUpsertBulk) ClearReversedAt() *InviteRewardLedgerUpsertBulk {
	return u.Update(func(s *InviteRewardLedgerUpsert) {
		s.ClearReversedAt()
	})
}

// Exec executes the query.
func (u *InviteRewardLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InviteRewardLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteRewardLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteRewardLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
