// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
)

// InvoiceRequestCreate is the builder for creating a InvoiceRequest entity.
type InvoiceRequestCreate struct {
	config
	mutation *InvoiceRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceRequestCreate) SetUserID(v int64) *InvoiceRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProfileID sets the "profile_id" field.
func (_c *InvoiceRequestCreate) SetProfileID(v int64) *InvoiceRequestCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableProfileID(v *int64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetProfileID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceRequestCreate) SetStatus(v string) *InvoiceRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableStatus(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceRequestCreate) SetAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetPaidTotal sets the "paid_total" field.
func (_c *InvoiceRequestCreate) SetPaidTotal(v float64) *InvoiceRequestCreate {
	_c.mutation.SetPaidTotal(v)
	return _c
}

// SetNillablePaidTotal sets the "paid_total" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillablePaidTotal(v *float64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetPaidTotal(*v)
	}
	return _c
}

// SetInvoicedTotal sets the "invoiced_total" field.
func (_c *InvoiceRequestCreate) SetInvoicedTotal(v float64) *InvoiceRequestCreate {
	_c.mutation.SetInvoicedTotal(v)
	return _c
}

// SetNillableInvoicedTotal sets the "invoiced_total" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoicedTotal(v *float64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoicedTotal(*v)
	}
	return _c
}

// SetReservedTotal sets the "reserved_total" field.
func (_c *InvoiceRequestCreate) SetReservedTotal(v float64) *InvoiceRequestCreate {
	_c.mutation.SetReservedTotal(v)
	return _c
}

// SetNillableReservedTotal sets the "reserved_total" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableReservedTotal(v *float64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetReservedTotal(*v)
	}
	return _c
}

// SetAvailableAmount sets the "available_amount" field.
func (_c *InvoiceRequestCreate) SetAvailableAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetAvailableAmount(v)
	return _c
}

// SetNillableAvailableAmount sets the "available_amount" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableAvailableAmount(v *float64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetAvailableAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *InvoiceRequestCreate) SetCurrency(v string) *InvoiceRequestCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCurrency(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetTitleType sets the "title_type" field.
func (_c *InvoiceRequestCreate) SetTitleType(v string) *InvoiceRequestCreate {
	_c.mutation.SetTitleType(v)
	return _c
}

// SetNillableTitleType sets the "title_type" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableTitleType(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetTitleType(*v)
	}
	return _c
}

// SetTitleName sets the "title_name" field.
func (_c *InvoiceRequestCreate) SetTitleName(v string) *InvoiceRequestCreate {
	_c.mutation.SetTitleName(v)
	return _c
}

// SetTaxNo sets the "tax_no" field.
func (_c *InvoiceRequestCreate) SetTaxNo(v string) *InvoiceRequestCreate {
	_c.mutation.SetTaxNo(v)
	return _c
}

// SetNillableTaxNo sets the "tax_no" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableTaxNo(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetTaxNo(*v)
	}
	return _c
}

// SetAddressPhone sets the "address_phone" field.
func (_c *InvoiceRequestCreate) SetAddressPhone(v string) *InvoiceRequestCreate {
	_c.mutation.SetAddressPhone(v)
	return _c
}

// SetNillableAddressPhone sets the "address_phone" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableAddressPhone(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetAddressPhone(*v)
	}
	return _c
}

// SetBankAccount sets the "bank_account" field.
func (_c *InvoiceRequestCreate) SetBankAccount(v string) *InvoiceRequestCreate {
	_c.mutation.SetBankAccount(v)
	return _c
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableBankAccount(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetBankAccount(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *InvoiceRequestCreate) SetEmail(v string) *InvoiceRequestCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *InvoiceRequestCreate) SetContent(v string) *InvoiceRequestCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetRemark sets the "remark" field.
func (_c *InvoiceRequestCreate) SetRemark(v string) *InvoiceRequestCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRemark(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetSdkCode sets the "sdk_code" field.
func (_c *InvoiceRequestCreate) SetSdkCode(v int) *InvoiceRequestCreate {
	_c.mutation.SetSdkCode(v)
	return _c
}

// SetNillableSdkCode sets the "sdk_code" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableSdkCode(v *int) *InvoiceRequestCreate {
	if v != nil {
		_c.SetSdkCode(*v)
	}
	return _c
}

// SetSdkMessage sets the "sdk_message" field.
func (_c *InvoiceRequestCreate) SetSdkMessage(v string) *InvoiceRequestCreate {
	_c.mutation.SetSdkMessage(v)
	return _c
}

// SetNillableSdkMessage sets the "sdk_message" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableSdkMessage(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetSdkMessage(*v)
	}
	return _c
}

// SetSdkResponse sets the "sdk_response" field.
func (_c *InvoiceRequestCreate) SetSdkResponse(v map[string]interface{}) *InvoiceRequestCreate {
	_c.mutation.SetSdkResponse(v)
	return _c
}

// SetInvoiceNo sets the "invoice_no" field.
func (_c *InvoiceRequestCreate) SetInvoiceNo(v string) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceNo(v)
	return _c
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceNo(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceNo(*v)
	}
	return _c
}

// SetInvoiceDate sets the "invoice_date" field.
func (_c *InvoiceRequestCreate) SetInvoiceDate(v string) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceDate(v)
	return _c
}

// SetNillableInvoiceDate sets the "invoice_date" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceDate(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceDate(*v)
	}
	return _c
}

// SetPdfURL sets the "pdf_url" field.
func (_c *InvoiceRequestCreate) SetPdfURL(v string) *InvoiceRequestCreate {
	_c.mutation.SetPdfURL(v)
	return _c
}

// SetNillablePdfURL sets the "pdf_url" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillablePdfURL(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetPdfURL(*v)
	}
	return _c
}

// SetOfdURL sets the "ofd_url" field.
func (_c *InvoiceRequestCreate) SetOfdURL(v string) *InvoiceRequestCreate {
	_c.mutation.SetOfdURL(v)
	return _c
}

// SetNillableOfdURL sets the "ofd_url" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableOfdURL(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetOfdURL(*v)
	}
	return _c
}

// SetXMLURL sets the "xml_url" field.
func (_c *InvoiceRequestCreate) SetXMLURL(v string) *InvoiceRequestCreate {
	_c.mutation.SetXMLURL(v)
	return _c
}

// SetNillableXMLURL sets the "xml_url" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableXMLURL(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetXMLURL(*v)
	}
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *InvoiceRequestCreate) SetIssuedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableIssuedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceRequestCreate) SetCreatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCreatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceRequestCreate) SetUpdatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_c *InvoiceRequestCreate) Mutation() *InvoiceRequestMutation {
	return _c.mutation
}

// Save creates the InvoiceRequest in the database.
func (_c *InvoiceRequestCreate) Save(ctx context.Context) (*InvoiceRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceRequestCreate) SaveX(ctx context.Context) *InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceRequestCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := invoicerequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PaidTotal(); !ok {
		v := invoicerequest.DefaultPaidTotal
		_c.mutation.SetPaidTotal(v)
	}
	if _, ok := _c.mutation.InvoicedTotal(); !ok {
		v := invoicerequest.DefaultInvoicedTotal
		_c.mutation.SetInvoicedTotal(v)
	}
	if _, ok := _c.mutation.ReservedTotal(); !ok {
		v := invoicerequest.DefaultReservedTotal
		_c.mutation.SetReservedTotal(v)
	}
	if _, ok := _c.mutation.AvailableAmount(); !ok {
		v := invoicerequest.DefaultAvailableAmount
		_c.mutation.SetAvailableAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := invoicerequest.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.TitleType(); !ok {
		v := invoicerequest.DefaultTitleType
		_c.mutation.SetTitleType(v)
	}
	if _, ok := _c.mutation.TaxNo(); !ok {
		v := invoicerequest.DefaultTaxNo
		_c.mutation.SetTaxNo(v)
	}
	if _, ok := _c.mutation.AddressPhone(); !ok {
		v := invoicerequest.DefaultAddressPhone
		_c.mutation.SetAddressPhone(v)
	}
	if _, ok := _c.mutation.BankAccount(); !ok {
		v := invoicerequest.DefaultBankAccount
		_c.mutation.SetBankAccount(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := invoicerequest.DefaultRemark
		_c.mutation.SetRemark(v)
	}
	if _, ok := _c.mutation.SdkMessage(); !ok {
		v := invoicerequest.DefaultSdkMessage
		_c.mutation.SetSdkMessage(v)
	}
	if _, ok := _c.mutation.InvoiceNo(); !ok {
		v := invoicerequest.DefaultInvoiceNo
		_c.mutation.SetInvoiceNo(v)
	}
	if _, ok := _c.mutation.InvoiceDate(); !ok {
		v := invoicerequest.DefaultInvoiceDate
		_c.mutation.SetInvoiceDate(v)
	}
	if _, ok := _c.mutation.PdfURL(); !ok {
		v := invoicerequest.DefaultPdfURL
		_c.mutation.SetPdfURL(v)
	}
	if _, ok := _c.mutation.OfdURL(); !ok {
		v := invoicerequest.DefaultOfdURL
		_c.mutation.SetOfdURL(v)
	}
	if _, ok := _c.mutation.XMLURL(); !ok {
		v := invoicerequest.DefaultXMLURL
		_c.mutation.SetXMLURL(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicerequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoicerequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceRequestCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceRequest.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "InvoiceRequest.amount"`)}
	}
	if _, ok := _c.mutation.PaidTotal(); !ok {
		return &ValidationError{Name: "paid_total", err: errors.New(`ent: missing required field "InvoiceRequest.paid_total"`)}
	}
	if _, ok := _c.mutation.InvoicedTotal(); !ok {
		return &ValidationError{Name: "invoiced_total", err: errors.New(`ent: missing required field "InvoiceRequest.invoiced_total"`)}
	}
	if _, ok := _c.mutation.ReservedTotal(); !ok {
		return &ValidationError{Name: "reserved_total", err: errors.New(`ent: missing required field "InvoiceRequest.reserved_total"`)}
	}
	if _, ok := _c.mutation.AvailableAmount(); !ok {
		return &ValidationError{Name: "available_amount", err: errors.New(`ent: missing required field "InvoiceRequest.available_amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "InvoiceRequest.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := invoicerequest.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TitleType(); !ok {
		return &ValidationError{Name: "title_type", err: errors.New(`ent: missing required field "InvoiceRequest.title_type"`)}
	}
	if v, ok := _c.mutation.TitleType(); ok {
		if err := invoicerequest.TitleTypeValidator(v); err != nil {
			return &ValidationError{Name: "title_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TitleName(); !ok {
		return &ValidationError{Name: "title_name", err: errors.New(`ent: missing required field "InvoiceRequest.title_name"`)}
	}
	if v, ok := _c.mutation.TitleName(); ok {
		if err := invoicerequest.TitleNameValidator(v); err != nil {
			return &ValidationError{Name: "title_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaxNo(); !ok {
		return &ValidationError{Name: "tax_no", err: errors.New(`ent: missing required field "InvoiceRequest.tax_no"`)}
	}
	if v, ok := _c.mutation.TaxNo(); ok {
		if err := invoicerequest.TaxNoValidator(v); err != nil {
			return &ValidationError{Name: "tax_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AddressPhone(); !ok {
		return &ValidationError{Name: "address_phone", err: errors.New(`ent: missing required field "InvoiceRequest.address_phone"`)}
	}
	if _, ok := _c.mutation.BankAccount(); !ok {
		return &ValidationError{Name: "bank_account", err: errors.New(`ent: missing required field "InvoiceRequest.bank_account"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "InvoiceRequest.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := invoicerequest.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "InvoiceRequest.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := invoicerequest.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "InvoiceRequest.remark"`)}
	}
	if _, ok := _c.mutation.SdkMessage(); !ok {
		return &ValidationError{Name: "sdk_message", err: errors.New(`ent: missing required field "InvoiceRequest.sdk_message"`)}
	}
	if _, ok := _c.mutation.InvoiceNo(); !ok {
		return &ValidationError{Name: "invoice_no", err: errors.New(`ent: missing required field "InvoiceRequest.invoice_no"`)}
	}
	if v, ok := _c.mutation.InvoiceNo(); ok {
		if err := invoicerequest.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InvoiceDate(); !ok {
		return &ValidationError{Name: "invoice_date", err: errors.New(`ent: missing required field "InvoiceRequest.invoice_date"`)}
	}
	if v, ok := _c.mutation.InvoiceDate(); ok {
		if err := invoicerequest.InvoiceDateValidator(v); err != nil {
			return &ValidationError{Name: "invoice_date", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_date": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PdfURL(); !ok {
		return &ValidationError{Name: "pdf_url", err: errors.New(`ent: missing required field "InvoiceRequest.pdf_url"`)}
	}
	if _, ok := _c.mutation.OfdURL(); !ok {
		return &ValidationError{Name: "ofd_url", err: errors.New(`ent: missing required field "InvoiceRequest.ofd_url"`)}
	}
	if _, ok := _c.mutation.XMLURL(); !ok {
		return &ValidationError{Name: "xml_url", err: errors.New(`ent: missing required field "InvoiceRequest.xml_url"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceRequest.updated_at"`)}
	}
	return nil
}

func (_c *InvoiceRequestCreate) sqlSave(ctx context.Context) (*InvoiceRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceRequestCreate) createSpec() (*InvoiceRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicerequest.Table, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(invoicerequest.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ProfileID(); ok {
		_spec.SetField(invoicerequest.FieldProfileID, field.TypeInt64, value)
		_node.ProfileID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoicerequest.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.PaidTotal(); ok {
		_spec.SetField(invoicerequest.FieldPaidTotal, field.TypeFloat64, value)
		_node.PaidTotal = value
	}
	if value, ok := _c.mutation.InvoicedTotal(); ok {
		_spec.SetField(invoicerequest.FieldInvoicedTotal, field.TypeFloat64, value)
		_node.InvoicedTotal = value
	}
	if value, ok := _c.mutation.ReservedTotal(); ok {
		_spec.SetField(invoicerequest.FieldReservedTotal, field.TypeFloat64, value)
		_node.ReservedTotal = value
	}
	if value, ok := _c.mutation.AvailableAmount(); ok {
		_spec.SetField(invoicerequest.FieldAvailableAmount, field.TypeFloat64, value)
		_node.AvailableAmount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(invoicerequest.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.TitleType(); ok {
		_spec.SetField(invoicerequest.FieldTitleType, field.TypeString, value)
		_node.TitleType = value
	}
	if value, ok := _c.mutation.TitleName(); ok {
		_spec.SetField(invoicerequest.FieldTitleName, field.TypeString, value)
		_node.TitleName = value
	}
	if value, ok := _c.mutation.TaxNo(); ok {
		_spec.SetField(invoicerequest.FieldTaxNo, field.TypeString, value)
		_node.TaxNo = value
	}
	if value, ok := _c.mutation.AddressPhone(); ok {
		_spec.SetField(invoicerequest.FieldAddressPhone, field.TypeString, value)
		_node.AddressPhone = value
	}
	if value, ok := _c.mutation.BankAccount(); ok {
		_spec.SetField(invoicerequest.FieldBankAccount, field.TypeString, value)
		_node.BankAccount = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(invoicerequest.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(invoicerequest.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(invoicerequest.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.SdkCode(); ok {
		_spec.SetField(invoicerequest.FieldSdkCode, field.TypeInt, value)
		_node.SdkCode = &value
	}
	if value, ok := _c.mutation.SdkMessage(); ok {
		_spec.SetField(invoicerequest.FieldSdkMessage, field.TypeString, value)
		_node.SdkMessage = value
	}
	if value, ok := _c.mutation.SdkResponse(); ok {
		_spec.SetField(invoicerequest.FieldSdkResponse, field.TypeJSON, value)
		_node.SdkResponse = value
	}
	if value, ok := _c.mutation.InvoiceNo(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceNo, field.TypeString, value)
		_node.InvoiceNo = value
	}
	if value, ok := _c.mutation.InvoiceDate(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceDate, field.TypeString, value)
		_node.InvoiceDate = value
	}
	if value, ok := _c.mutation.PdfURL(); ok {
		_spec.SetField(invoicerequest.FieldPdfURL, field.TypeString, value)
		_node.PdfURL = value
	}
	if value, ok := _c.mutation.OfdURL(); ok {
		_spec.SetField(invoicerequest.FieldOfdURL, field.TypeString, value)
		_node.OfdURL = value
	}
	if value, ok := _c.mutation.XMLURL(); ok {
		_spec.SetField(invoicerequest.FieldXMLURL, field.TypeString, value)
		_node.XMLURL = value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicerequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertOne {
	_c.conflict = opts
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflictColumns(columns ...string) *InvoiceRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceRequestUpsertOne is the builder for "upsert"-ing
	//  one InvoiceRequest node.
	InvoiceRequestUpsertOne struct {
		create *InvoiceRequestCreate
	}

	// InvoiceRequestUpsert is the "OnConflict" setter.
	InvoiceRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsert) SetUserID(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUserID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceRequestUpsert) AddUserID(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldUserID, v)
	return u
}

// SetProfileID sets the "profile_id" field.
func (u *InvoiceRequestUpsert) SetProfileID(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldProfileID, v)
	return u
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateProfileID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldProfileID)
	return u
}

// AddProfileID adds v to the "profile_id" field.
func (u *InvoiceRequestUpsert) AddProfileID(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldProfileID, v)
	return u
}

// ClearProfileID clears the value of the "profile_id" field.
func (u *InvoiceRequestUpsert) ClearProfileID() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldProfileID)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsert) SetStatus(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateStatus() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldStatus)
	return u
}

// SetAmount sets the "amount" field.
func (u *InvoiceRequestUpsert) SetAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceRequestUpsert) AddAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldAmount, v)
	return u
}

// SetPaidTotal sets the "paid_total" field.
func (u *InvoiceRequestUpsert) SetPaidTotal(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldPaidTotal, v)
	return u
}

// UpdatePaidTotal sets the "paid_total" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdatePaidTotal() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldPaidTotal)
	return u
}

// AddPaidTotal adds v to the "paid_total" field.
func (u *InvoiceRequestUpsert) AddPaidTotal(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldPaidTotal, v)
	return u
}

// SetInvoicedTotal sets the "invoiced_total" field.
func (u *InvoiceRequestUpsert) SetInvoicedTotal(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoicedTotal, v)
	return u
}

// UpdateInvoicedTotal sets the "invoiced_total" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoicedTotal() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoicedTotal)
	return u
}

// AddInvoicedTotal adds v to the "invoiced_total" field.
func (u *InvoiceRequestUpsert) AddInvoicedTotal(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldInvoicedTotal, v)
	return u
}

// SetReservedTotal sets the "reserved_total" field.
func (u *InvoiceRequestUpsert) SetReservedTotal(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldReservedTotal, v)
	return u
}

// UpdateReservedTotal sets the "reserved_total" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateReservedTotal() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldReservedTotal)
	return u
}

// AddReservedTotal adds v to the "reserved_total" field.
func (u *InvoiceRequestUpsert) AddReservedTotal(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldReservedTotal, v)
	return u
}

// SetAvailableAmount sets the "available_amount" field.
func (u *InvoiceRequestUpsert) SetAvailableAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldAvailableAmount, v)
	return u
}

// UpdateAvailableAmount sets the "available_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateAvailableAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldAvailableAmount)
	return u
}

// AddAvailableAmount adds v to the "available_amount" field.
func (u *InvoiceRequestUpsert) AddAvailableAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldAvailableAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *InvoiceRequestUpsert) SetCurrency(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateCurrency() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldCurrency)
	return u
}

// SetTitleType sets the "title_type" field.
func (u *InvoiceRequestUpsert) SetTitleType(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTitleType, v)
	return u
}

// UpdateTitleType sets the "title_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTitleType() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTitleType)
	return u
}

// SetTitleName sets the "title_name" field.
func (u *InvoiceRequestUpsert) SetTitleName(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTitleName, v)
	return u
}

// UpdateTitleName sets the "title_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTitleName() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTitleName)
	return u
}

// SetTaxNo sets the "tax_no" field.
func (u *InvoiceRequestUpsert) SetTaxNo(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTaxNo, v)
	return u
}

// UpdateTaxNo sets the "tax_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTaxNo() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTaxNo)
	return u
}

// SetAddressPhone sets the "address_phone" field.
func (u *InvoiceRequestUpsert) SetAddressPhone(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldAddressPhone, v)
	return u
}

// UpdateAddressPhone sets the "address_phone" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateAddressPhone() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldAddressPhone)
	return u
}

// SetBankAccount sets the "bank_account" field.
func (u *InvoiceRequestUpsert) SetBankAccount(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldBankAccount, v)
	return u
}

// UpdateBankAccount sets the "bank_account" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateBankAccount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldBankAccount)
	return u
}

// SetEmail sets the "email" field.
func (u *InvoiceRequestUpsert) SetEmail(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateEmail() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldEmail)
	return u
}

// SetContent sets the "content" field.
func (u *InvoiceRequestUpsert) SetContent(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateContent() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldContent)
	return u
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsert) SetRemark(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRemark() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRemark)
	return u
}

// SetSdkCode sets the "sdk_code" field.
func (u *InvoiceRequestUpsert) SetSdkCode(v int) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldSdkCode, v)
	return u
}

// UpdateSdkCode sets the "sdk_code" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateSdkCode() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldSdkCode)
	return u
}

// AddSdkCode adds v to the "sdk_code" field.
func (u *InvoiceRequestUpsert) AddSdkCode(v int) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldSdkCode, v)
	return u
}

// ClearSdkCode clears the value of the "sdk_code" field.
func (u *InvoiceRequestUpsert) ClearSdkCode() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldSdkCode)
	return u
}

// SetSdkMessage sets the "sdk_message" field.
func (u *InvoiceRequestUpsert) SetSdkMessage(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldSdkMessage, v)
	return u
}

// UpdateSdkMessage sets the "sdk_message" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateSdkMessage() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldSdkMessage)
	return u
}

// SetSdkResponse sets the "sdk_response" field.
func (u *InvoiceRequestUpsert) SetSdkResponse(v map[string]interface{}) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldSdkResponse, v)
	return u
}

// UpdateSdkResponse sets the "sdk_response" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateSdkResponse() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldSdkResponse)
	return u
}

// ClearSdkResponse clears the value of the "sdk_response" field.
func (u *InvoiceRequestUpsert) ClearSdkResponse() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldSdkResponse)
	return u
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceRequestUpsert) SetInvoiceNo(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceNo, v)
	return u
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceNo() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceNo)
	return u
}

// SetInvoiceDate sets the "invoice_date" field.
func (u *InvoiceRequestUpsert) SetInvoiceDate(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceDate, v)
	return u
}

// UpdateInvoiceDate sets the "invoice_date" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceDate() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceDate)
	return u
}

// SetPdfURL sets the "pdf_url" field.
func (u *InvoiceRequestUpsert) SetPdfURL(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldPdfURL, v)
	return u
}

// UpdatePdfURL sets the "pdf_url" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdatePdfURL() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldPdfURL)
	return u
}

// SetOfdURL sets the "ofd_url" field.
func (u *InvoiceRequestUpsert) SetOfdURL(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldOfdURL, v)
	return u
}

// UpdateOfdURL sets the "ofd_url" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateOfdURL() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldOfdURL)
	return u
}

// SetXMLURL sets the "xml_url" field.
func (u *InvoiceRequestUpsert) SetXMLURL(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldXMLURL, v)
	return u
}

// UpdateXMLURL sets the "xml_url" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateXMLURL() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldXMLURL)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsert) SetIssuedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateIssuedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldIssuedAt)
	return u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsert) ClearIssuedAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldIssuedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsert) SetUpdatedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUpdatedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertOne) UpdateNewValues() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicerequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceRequestUpsertOne) Ignore() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertOne) DoNothing() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreate.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertOne) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertOne) SetUserID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceRequestUpsertOne) AddUserID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUserID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetProfileID sets the "profile_id" field.
func (u *InvoiceRequestUpsertOne) SetProfileID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetProfileID(v)
	})
}

// AddProfileID adds v to the "profile_id" field.
func (u *InvoiceRequestUpsertOne) AddProfileID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddProfileID(v)
	})
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateProfileID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateProfileID()
	})
}

// ClearProfileID clears the value of the "profile_id" field.
func (u *InvoiceRequestUpsertOne) ClearProfileID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearProfileID()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertOne) SetStatus(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateStatus() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceRequestUpsertOne) SetAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceRequestUpsertOne) AddAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetPaidTotal sets the "paid_total" field.
func (u *InvoiceRequestUpsertOne) SetPaidTotal(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetPaidTotal(v)
	})
}

// AddPaidTotal adds v to the "paid_total" field.
func (u *InvoiceRequestUpsertOne) AddPaidTotal(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddPaidTotal(v)
	})
}

// UpdatePaidTotal sets the "paid_total" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdatePaidTotal() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdatePaidTotal()
	})
}

// SetInvoicedTotal sets the "invoiced_total" field.
func (u *InvoiceRequestUpsertOne) SetInvoicedTotal(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoicedTotal(v)
	})
}

// AddInvoicedTotal adds v to the "invoiced_total" field.
func (u *InvoiceRequestUpsertOne) AddInvoicedTotal(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddInvoicedTotal(v)
	})
}

// UpdateInvoicedTotal sets the "invoiced_total" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoicedTotal() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoicedTotal()
	})
}

// SetReservedTotal sets the "reserved_total" field.
func (u *InvoiceRequestUpsertOne) SetReservedTotal(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetReservedTotal(v)
	})
}

// AddReservedTotal adds v to the "reserved_total" field.
func (u *InvoiceRequestUpsertOne) AddReservedTotal(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddReservedTotal(v)
	})
}

// UpdateReservedTotal sets the "reserved_total" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateReservedTotal() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateReservedTotal()
	})
}

// SetAvailableAmount sets the "available_amount" field.
func (u *InvoiceRequestUpsertOne) SetAvailableAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAvailableAmount(v)
	})
}

// AddAvailableAmount adds v to the "available_amount" field.
func (u *InvoiceRequestUpsertOne) AddAvailableAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddAvailableAmount(v)
	})
}

// UpdateAvailableAmount sets the "available_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateAvailableAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAvailableAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceRequestUpsertOne) SetCurrency(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateCurrency() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCurrency()
	})
}

// SetTitleType sets the "title_type" field.
func (u *InvoiceRequestUpsertOne) SetTitleType(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitleType(v)
	})
}

// UpdateTitleType sets the "title_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTitleType() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitleType()
	})
}

// SetTitleName sets the "title_name" field.
func (u *InvoiceRequestUpsertOne) SetTitleName(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitleName(v)
	})
}

// UpdateTitleName sets the "title_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTitleName() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitleName()
	})
}

// SetTaxNo sets the "tax_no" field.
func (u *InvoiceRequestUpsertOne) SetTaxNo(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxNo(v)
	})
}

// UpdateTaxNo sets the "tax_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTaxNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxNo()
	})
}

// SetAddressPhone sets the "address_phone" field.
func (u *InvoiceRequestUpsertOne) SetAddressPhone(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAddressPhone(v)
	})
}

// UpdateAddressPhone sets the "address_phone" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateAddressPhone() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAddressPhone()
	})
}

// SetBankAccount sets the "bank_account" field.
func (u *InvoiceRequestUpsertOne) SetBankAccount(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetBankAccount(v)
	})
}

// UpdateBankAccount sets the "bank_account" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateBankAccount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateBankAccount()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceRequestUpsertOne) SetEmail(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateEmail() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateEmail()
	})
}

// SetContent sets the "content" field.
func (u *InvoiceRequestUpsertOne) SetContent(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateContent() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateContent()
	})
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsertOne) SetRemark(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemark()
	})
}

// SetSdkCode sets the "sdk_code" field.
func (u *InvoiceRequestUpsertOne) SetSdkCode(v int) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSdkCode(v)
	})
}

// AddSdkCode adds v to the "sdk_code" field.
func (u *InvoiceRequestUpsertOne) AddSdkCode(v int) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddSdkCode(v)
	})
}

// UpdateSdkCode sets the "sdk_code" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateSdkCode() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSdkCode()
	})
}

// ClearSdkCode clears the value of the "sdk_code" field.
func (u *InvoiceRequestUpsertOne) ClearSdkCode() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearSdkCode()
	})
}

// SetSdkMessage sets the "sdk_message" field.
func (u *InvoiceRequestUpsertOne) SetSdkMessage(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSdkMessage(v)
	})
}

// UpdateSdkMessage sets the "sdk_message" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateSdkMessage() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSdkMessage()
	})
}

// SetSdkResponse sets the "sdk_response" field.
func (u *InvoiceRequestUpsertOne) SetSdkResponse(v map[string]interface{}) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSdkResponse(v)
	})
}

// UpdateSdkResponse sets the "sdk_response" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateSdkResponse() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSdkResponse()
	})
}

// ClearSdkResponse clears the value of the "sdk_response" field.
func (u *InvoiceRequestUpsertOne) ClearSdkResponse() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearSdkResponse()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceNo(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceNo() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceNo()
	})
}

// SetInvoiceDate sets the "invoice_date" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceDate(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceDate(v)
	})
}

// UpdateInvoiceDate sets the "invoice_date" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceDate() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceDate()
	})
}

// SetPdfURL sets the "pdf_url" field.
func (u *InvoiceRequestUpsertOne) SetPdfURL(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetPdfURL(v)
	})
}

// UpdatePdfURL sets the "pdf_url" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdatePdfURL() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdatePdfURL()
	})
}

// SetOfdURL sets the "ofd_url" field.
func (u *InvoiceRequestUpsertOne) SetOfdURL(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetOfdURL(v)
	})
}

// UpdateOfdURL sets the "ofd_url" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateOfdURL() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateOfdURL()
	})
}

// SetXMLURL sets the "xml_url" field.
func (u *InvoiceRequestUpsertOne) SetXMLURL(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetXMLURL(v)
	})
}

// UpdateXMLURL sets the "xml_url" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateXMLURL() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateXMLURL()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertOne) SetIssuedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertOne) ClearIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertOne) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUpdatedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceRequestCreateBulk is the builder for creating many InvoiceRequest entities in bulk.
type InvoiceRequestCreateBulk struct {
	config
	err      error
	builders []*InvoiceRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceRequest entities in the database.
func (_c *InvoiceRequestCreateBulk) Save(ctx context.Context) ([]*InvoiceRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) SaveX(ctx context.Context) []*InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertBulk {
	_c.conflict = opts
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflictColumns(columns ...string) *InvoiceRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// InvoiceRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceRequest nodes.
type InvoiceRequestUpsertBulk struct {
	create *InvoiceRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) UpdateNewValues() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicerequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) Ignore() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertBulk) DoNothing() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertBulk) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertBulk) SetUserID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceRequestUpsertBulk) AddUserID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUserID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetProfileID sets the "profile_id" field.
func (u *InvoiceRequestUpsertBulk) SetProfileID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetProfileID(v)
	})
}

// AddProfileID adds v to the "profile_id" field.
func (u *InvoiceRequestUpsertBulk) AddProfileID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddProfileID(v)
	})
}

// UpdateProfileID sets the "profile_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateProfileID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateProfileID()
	})
}

// ClearProfileID clears the value of the "profile_id" field.
func (u *InvoiceRequestUpsertBulk) ClearProfileID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearProfileID()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertBulk) SetStatus(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateStatus() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceRequestUpsertBulk) SetAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceRequestUpsertBulk) AddAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetPaidTotal sets the "paid_total" field.
func (u *InvoiceRequestUpsertBulk) SetPaidTotal(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetPaidTotal(v)
	})
}

// AddPaidTotal adds v to the "paid_total" field.
func (u *InvoiceRequestUpsertBulk) AddPaidTotal(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddPaidTotal(v)
	})
}

// UpdatePaidTotal sets the "paid_total" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdatePaidTotal() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdatePaidTotal()
	})
}

// SetInvoicedTotal sets the "invoiced_total" field.
func (u *InvoiceRequestUpsertBulk) SetInvoicedTotal(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoicedTotal(v)
	})
}

// AddInvoicedTotal adds v to the "invoiced_total" field.
func (u *InvoiceRequestUpsertBulk) AddInvoicedTotal(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddInvoicedTotal(v)
	})
}

// UpdateInvoicedTotal sets the "invoiced_total" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoicedTotal() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoicedTotal()
	})
}

// SetReservedTotal sets the "reserved_total" field.
func (u *InvoiceRequestUpsertBulk) SetReservedTotal(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetReservedTotal(v)
	})
}

// AddReservedTotal adds v to the "reserved_total" field.
func (u *InvoiceRequestUpsertBulk) AddReservedTotal(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddReservedTotal(v)
	})
}

// UpdateReservedTotal sets the "reserved_total" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateReservedTotal() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateReservedTotal()
	})
}

// SetAvailableAmount sets the "available_amount" field.
func (u *InvoiceRequestUpsertBulk) SetAvailableAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAvailableAmount(v)
	})
}

// AddAvailableAmount adds v to the "available_amount" field.
func (u *InvoiceRequestUpsertBulk) AddAvailableAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddAvailableAmount(v)
	})
}

// UpdateAvailableAmount sets the "available_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateAvailableAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAvailableAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceRequestUpsertBulk) SetCurrency(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateCurrency() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateCurrency()
	})
}

// SetTitleType sets the "title_type" field.
func (u *InvoiceRequestUpsertBulk) SetTitleType(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitleType(v)
	})
}

// UpdateTitleType sets the "title_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTitleType() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitleType()
	})
}

// SetTitleName sets the "title_name" field.
func (u *InvoiceRequestUpsertBulk) SetTitleName(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitleName(v)
	})
}

// UpdateTitleName sets the "title_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTitleName() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitleName()
	})
}

// SetTaxNo sets the "tax_no" field.
func (u *InvoiceRequestUpsertBulk) SetTaxNo(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxNo(v)
	})
}

// UpdateTaxNo sets the "tax_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTaxNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxNo()
	})
}

// SetAddressPhone sets the "address_phone" field.
func (u *InvoiceRequestUpsertBulk) SetAddressPhone(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAddressPhone(v)
	})
}

// UpdateAddressPhone sets the "address_phone" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateAddressPhone() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAddressPhone()
	})
}

// SetBankAccount sets the "bank_account" field.
func (u *InvoiceRequestUpsertBulk) SetBankAccount(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetBankAccount(v)
	})
}

// UpdateBankAccount sets the "bank_account" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateBankAccount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateBankAccount()
	})
}

// SetEmail sets the "email" field.
func (u *InvoiceRequestUpsertBulk) SetEmail(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateEmail() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateEmail()
	})
}

// SetContent sets the "content" field.
func (u *InvoiceRequestUpsertBulk) SetContent(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateContent() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateContent()
	})
}

// SetRemark sets the "remark" field.
func (u *InvoiceRequestUpsertBulk) SetRemark(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRemark()
	})
}

// SetSdkCode sets the "sdk_code" field.
func (u *InvoiceRequestUpsertBulk) SetSdkCode(v int) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSdkCode(v)
	})
}

// AddSdkCode adds v to the "sdk_code" field.
func (u *InvoiceRequestUpsertBulk) AddSdkCode(v int) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddSdkCode(v)
	})
}

// UpdateSdkCode sets the "sdk_code" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateSdkCode() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSdkCode()
	})
}

// ClearSdkCode clears the value of the "sdk_code" field.
func (u *InvoiceRequestUpsertBulk) ClearSdkCode() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearSdkCode()
	})
}

// SetSdkMessage sets the "sdk_message" field.
func (u *InvoiceRequestUpsertBulk) SetSdkMessage(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSdkMessage(v)
	})
}

// UpdateSdkMessage sets the "sdk_message" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateSdkMessage() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSdkMessage()
	})
}

// SetSdkResponse sets the "sdk_response" field.
func (u *InvoiceRequestUpsertBulk) SetSdkResponse(v map[string]interface{}) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetSdkResponse(v)
	})
}

// UpdateSdkResponse sets the "sdk_response" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateSdkResponse() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateSdkResponse()
	})
}

// ClearSdkResponse clears the value of the "sdk_response" field.
func (u *InvoiceRequestUpsertBulk) ClearSdkResponse() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearSdkResponse()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceNo(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceNo() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceNo()
	})
}

// SetInvoiceDate sets the "invoice_date" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceDate(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceDate(v)
	})
}

// UpdateInvoiceDate sets the "invoice_date" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceDate() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceDate()
	})
}

// SetPdfURL sets the "pdf_url" field.
func (u *InvoiceRequestUpsertBulk) SetPdfURL(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetPdfURL(v)
	})
}

// UpdatePdfURL sets the "pdf_url" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdatePdfURL() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdatePdfURL()
	})
}

// SetOfdURL sets the "ofd_url" field.
func (u *InvoiceRequestUpsertBulk) SetOfdURL(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetOfdURL(v)
	})
}

// UpdateOfdURL sets the "ofd_url" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateOfdURL() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateOfdURL()
	})
}

// SetXMLURL sets the "xml_url" field.
func (u *InvoiceRequestUpsertBulk) SetXMLURL(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetXMLURL(v)
	})
}

// UpdateXMLURL sets the "xml_url" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateXMLURL() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateXMLURL()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) SetIssuedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) ClearIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUpdatedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
