// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicedocument"
)

// InvoiceDocumentCreate is the builder for creating a InvoiceDocument entity.
type InvoiceDocumentCreate struct {
	config
	mutation *InvoiceDocumentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (_c *InvoiceDocumentCreate) SetInvoiceRequestID(v int64) *InvoiceDocumentCreate {
	_c.mutation.SetInvoiceRequestID(v)
	return _c
}

// SetInvoiceNo sets the "invoice_no" field.
func (_c *InvoiceDocumentCreate) SetInvoiceNo(v string) *InvoiceDocumentCreate {
	_c.mutation.SetInvoiceNo(v)
	return _c
}

// SetNillableInvoiceNo sets the "invoice_no" field if the given value is not nil.
func (_c *InvoiceDocumentCreate) SetNillableInvoiceNo(v *string) *InvoiceDocumentCreate {
	if v != nil {
		_c.SetInvoiceNo(*v)
	}
	return _c
}

// SetInvoiceCode sets the "invoice_code" field.
func (_c *InvoiceDocumentCreate) SetInvoiceCode(v string) *InvoiceDocumentCreate {
	_c.mutation.SetInvoiceCode(v)
	return _c
}

// SetNillableInvoiceCode sets the "invoice_code" field if the given value is not nil.
func (_c *InvoiceDocumentCreate) SetNillableInvoiceCode(v *string) *InvoiceDocumentCreate {
	if v != nil {
		_c.SetInvoiceCode(*v)
	}
	return _c
}

// SetFileURL sets the "file_url" field.
func (_c *InvoiceDocumentCreate) SetFileURL(v string) *InvoiceDocumentCreate {
	_c.mutation.SetFileURL(v)
	return _c
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_c *InvoiceDocumentCreate) SetNillableFileURL(v *string) *InvoiceDocumentCreate {
	if v != nil {
		_c.SetFileURL(*v)
	}
	return _c
}

// SetFileType sets the "file_type" field.
func (_c *InvoiceDocumentCreate) SetFileType(v string) *InvoiceDocumentCreate {
	_c.mutation.SetFileType(v)
	return _c
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_c *InvoiceDocumentCreate) SetNillableFileType(v *string) *InvoiceDocumentCreate {
	if v != nil {
		_c.SetFileType(*v)
	}
	return _c
}

// SetRawPayloadSummary sets the "raw_payload_summary" field.
func (_c *InvoiceDocumentCreate) SetRawPayloadSummary(v map[string]interface{}) *InvoiceDocumentCreate {
	_c.mutation.SetRawPayloadSummary(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceDocumentCreate) SetCreatedAt(v time.Time) *InvoiceDocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceDocumentCreate) SetNillableCreatedAt(v *time.Time) *InvoiceDocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the InvoiceDocumentMutation object of the builder.
func (_c *InvoiceDocumentCreate) Mutation() *InvoiceDocumentMutation {
	return _c.mutation
}

// Save creates the InvoiceDocument in the database.
func (_c *InvoiceDocumentCreate) Save(ctx context.Context) (*InvoiceDocument, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceDocumentCreate) SaveX(ctx context.Context) *InvoiceDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceDocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceDocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceDocumentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicedocument.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceDocumentCreate) check() error {
	if _, ok := _c.mutation.InvoiceRequestID(); !ok {
		return &ValidationError{Name: "invoice_request_id", err: errors.New(`ent: missing required field "InvoiceDocument.invoice_request_id"`)}
	}
	if v, ok := _c.mutation.InvoiceNo(); ok {
		if err := invoicedocument.InvoiceNoValidator(v); err != nil {
			return &ValidationError{Name: "invoice_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceDocument.invoice_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.InvoiceCode(); ok {
		if err := invoicedocument.InvoiceCodeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceDocument.invoice_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FileType(); ok {
		if err := invoicedocument.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceDocument.file_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceDocument.created_at"`)}
	}
	return nil
}

func (_c *InvoiceDocumentCreate) sqlSave(ctx context.Context) (*InvoiceDocument, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceDocumentCreate) createSpec() (*InvoiceDocument, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceDocument{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicedocument.Table, sqlgraph.NewFieldSpec(invoicedocument.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InvoiceRequestID(); ok {
		_spec.SetField(invoicedocument.FieldInvoiceRequestID, field.TypeInt64, value)
		_node.InvoiceRequestID = value
	}
	if value, ok := _c.mutation.InvoiceNo(); ok {
		_spec.SetField(invoicedocument.FieldInvoiceNo, field.TypeString, value)
		_node.InvoiceNo = &value
	}
	if value, ok := _c.mutation.InvoiceCode(); ok {
		_spec.SetField(invoicedocument.FieldInvoiceCode, field.TypeString, value)
		_node.InvoiceCode = &value
	}
	if value, ok := _c.mutation.FileURL(); ok {
		_spec.SetField(invoicedocument.FieldFileURL, field.TypeString, value)
		_node.FileURL = &value
	}
	if value, ok := _c.mutation.FileType(); ok {
		_spec.SetField(invoicedocument.FieldFileType, field.TypeString, value)
		_node.FileType = &value
	}
	if value, ok := _c.mutation.RawPayloadSummary(); ok {
		_spec.SetField(invoicedocument.FieldRawPayloadSummary, field.TypeJSON, value)
		_node.RawPayloadSummary = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicedocument.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceDocument.Create().
//		SetInvoiceRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceDocumentUpsert) {
//			SetInvoiceRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceDocumentCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceDocumentUpsertOne {
	_c.conflict = opts
	return &InvoiceDocumentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceDocumentCreate) OnConflictColumns(columns ...string) *InvoiceDocumentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceDocumentUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceDocumentUpsertOne is the builder for "upsert"-ing
	//  one InvoiceDocument node.
	InvoiceDocumentUpsertOne struct {
		create *InvoiceDocumentCreate
	}

	// InvoiceDocumentUpsert is the "OnConflict" setter.
	InvoiceDocumentUpsert struct {
		*sql.UpdateSet
	}
)

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (u *InvoiceDocumentUpsert) SetInvoiceRequestID(v int64) *InvoiceDocumentUpsert {
	u.Set(invoicedocument.FieldInvoiceRequestID, v)
	return u
}

// UpdateInvoiceRequestID sets the "invoice_request_id" field to the value that was provided on create.
func (u *InvoiceDocumentUpsert) UpdateInvoiceRequestID() *InvoiceDocumentUpsert {
	u.SetExcluded(invoicedocument.FieldInvoiceRequestID)
	return u
}

// AddInvoiceRequestID adds v to the "invoice_request_id" field.
func (u *InvoiceDocumentUpsert) AddInvoiceRequestID(v int64) *InvoiceDocumentUpsert {
	u.Add(invoicedocument.FieldInvoiceRequestID, v)
	return u
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceDocumentUpsert) SetInvoiceNo(v string) *InvoiceDocumentUpsert {
	u.Set(invoicedocument.FieldInvoiceNo, v)
	return u
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceDocumentUpsert) UpdateInvoiceNo() *InvoiceDocumentUpsert {
	u.SetExcluded(invoicedocument.FieldInvoiceNo)
	return u
}

// ClearInvoiceNo clears the value of the "invoice_no" field.
func (u *InvoiceDocumentUpsert) ClearInvoiceNo() *InvoiceDocumentUpsert {
	u.SetNull(invoicedocument.FieldInvoiceNo)
	return u
}

// SetInvoiceCode sets the "invoice_code" field.
func (u *InvoiceDocumentUpsert) SetInvoiceCode(v string) *InvoiceDocumentUpsert {
	u.Set(invoicedocument.FieldInvoiceCode, v)
	return u
}

// UpdateInvoiceCode sets the "invoice_code" field to the value that was provided on create.
func (u *InvoiceDocumentUpsert) UpdateInvoiceCode() *InvoiceDocumentUpsert {
	u.SetExcluded(invoicedocument.FieldInvoiceCode)
	return u
}

// ClearInvoiceCode clears the value of the "invoice_code" field.
func (u *InvoiceDocumentUpsert) ClearInvoiceCode() *InvoiceDocumentUpsert {
	u.SetNull(invoicedocument.FieldInvoiceCode)
	return u
}

// SetFileURL sets the "file_url" field.
func (u *InvoiceDocumentUpsert) SetFileURL(v string) *InvoiceDocumentUpsert {
	u.Set(invoicedocument.FieldFileURL, v)
	return u
}

// UpdateFileURL sets the "file_url" field to the value that was provided on create.
func (u *InvoiceDocumentUpsert) UpdateFileURL() *InvoiceDocumentUpsert {
	u.SetExcluded(invoicedocument.FieldFileURL)
	return u
}

// ClearFileURL clears the value of the "file_url" field.
func (u *InvoiceDocumentUpsert) ClearFileURL() *InvoiceDocumentUpsert {
	u.SetNull(invoicedocument.FieldFileURL)
	return u
}

// SetFileType sets the "file_type" field.
func (u *InvoiceDocumentUpsert) SetFileType(v string) *InvoiceDocumentUpsert {
	u.Set(invoicedocument.FieldFileType, v)
	return u
}

// UpdateFileType sets the "file_type" field to the value that was provided on create.
func (u *InvoiceDocumentUpsert) UpdateFileType() *InvoiceDocumentUpsert {
	u.SetExcluded(invoicedocument.FieldFileType)
	return u
}

// ClearFileType clears the value of the "file_type" field.
func (u *InvoiceDocumentUpsert) ClearFileType() *InvoiceDocumentUpsert {
	u.SetNull(invoicedocument.FieldFileType)
	return u
}

// SetRawPayloadSummary sets the "raw_payload_summary" field.
func (u *InvoiceDocumentUpsert) SetRawPayloadSummary(v map[string]interface{}) *InvoiceDocumentUpsert {
	u.Set(invoicedocument.FieldRawPayloadSummary, v)
	return u
}

// UpdateRawPayloadSummary sets the "raw_payload_summary" field to the value that was provided on create.
func (u *InvoiceDocumentUpsert) UpdateRawPayloadSummary() *InvoiceDocumentUpsert {
	u.SetExcluded(invoicedocument.FieldRawPayloadSummary)
	return u
}

// ClearRawPayloadSummary clears the value of the "raw_payload_summary" field.
func (u *InvoiceDocumentUpsert) ClearRawPayloadSummary() *InvoiceDocumentUpsert {
	u.SetNull(invoicedocument.FieldRawPayloadSummary)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceDocumentUpsertOne) UpdateNewValues() *InvoiceDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicedocument.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceDocument.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceDocumentUpsertOne) Ignore() *InvoiceDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceDocumentUpsertOne) DoNothing() *InvoiceDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceDocumentCreate.OnConflict
// documentation for more info.
func (u *InvoiceDocumentUpsertOne) Update(set func(*InvoiceDocumentUpsert)) *InvoiceDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (u *InvoiceDocumentUpsertOne) SetInvoiceRequestID(v int64) *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetInvoiceRequestID(v)
	})
}

// AddInvoiceRequestID adds v to the "invoice_request_id" field.
func (u *InvoiceDocumentUpsertOne) AddInvoiceRequestID(v int64) *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.AddInvoiceRequestID(v)
	})
}

// UpdateInvoiceRequestID sets the "invoice_request_id" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertOne) UpdateInvoiceRequestID() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateInvoiceRequestID()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceDocumentUpsertOne) SetInvoiceNo(v string) *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertOne) UpdateInvoiceNo() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateInvoiceNo()
	})
}

// ClearInvoiceNo clears the value of the "invoice_no" field.
func (u *InvoiceDocumentUpsertOne) ClearInvoiceNo() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearInvoiceNo()
	})
}

// SetInvoiceCode sets the "invoice_code" field.
func (u *InvoiceDocumentUpsertOne) SetInvoiceCode(v string) *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetInvoiceCode(v)
	})
}

// UpdateInvoiceCode sets the "invoice_code" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertOne) UpdateInvoiceCode() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateInvoiceCode()
	})
}

// ClearInvoiceCode clears the value of the "invoice_code" field.
func (u *InvoiceDocumentUpsertOne) ClearInvoiceCode() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearInvoiceCode()
	})
}

// SetFileURL sets the "file_url" field.
func (u *InvoiceDocumentUpsertOne) SetFileURL(v string) *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetFileURL(v)
	})
}

// UpdateFileURL sets the "file_url" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertOne) UpdateFileURL() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateFileURL()
	})
}

// ClearFileURL clears the value of the "file_url" field.
func (u *InvoiceDocumentUpsertOne) ClearFileURL() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearFileURL()
	})
}

// SetFileType sets the "file_type" field.
func (u *InvoiceDocumentUpsertOne) SetFileType(v string) *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetFileType(v)
	})
}

// UpdateFileType sets the "file_type" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertOne) UpdateFileType() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateFileType()
	})
}

// ClearFileType clears the value of the "file_type" field.
func (u *InvoiceDocumentUpsertOne) ClearFileType() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearFileType()
	})
}

// SetRawPayloadSummary sets the "raw_payload_summary" field.
func (u *InvoiceDocumentUpsertOne) SetRawPayloadSummary(v map[string]interface{}) *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetRawPayloadSummary(v)
	})
}

// UpdateRawPayloadSummary sets the "raw_payload_summary" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertOne) UpdateRawPayloadSummary() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateRawPayloadSummary()
	})
}

// ClearRawPayloadSummary clears the value of the "raw_payload_summary" field.
func (u *InvoiceDocumentUpsertOne) ClearRawPayloadSummary() *InvoiceDocumentUpsertOne {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearRawPayloadSummary()
	})
}

// Exec executes the query.
func (u *InvoiceDocumentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceDocumentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceDocumentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceDocumentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceDocumentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceDocumentCreateBulk is the builder for creating many InvoiceDocument entities in bulk.
type InvoiceDocumentCreateBulk struct {
	config
	err      error
	builders []*InvoiceDocumentCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceDocument entities in the database.
func (_c *InvoiceDocumentCreateBulk) Save(ctx context.Context) ([]*InvoiceDocument, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceDocument, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceDocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceDocumentCreateBulk) SaveX(ctx context.Context) []*InvoiceDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceDocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceDocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceDocument.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceDocumentUpsert) {
//			SetInvoiceRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceDocumentCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceDocumentUpsertBulk {
	_c.conflict = opts
	return &InvoiceDocumentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceDocumentCreateBulk) OnConflictColumns(columns ...string) *InvoiceDocumentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceDocumentUpsertBulk{
		create: _c,
	}
}

// InvoiceDocumentUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceDocument nodes.
type InvoiceDocumentUpsertBulk struct {
	create *InvoiceDocumentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceDocumentUpsertBulk) UpdateNewValues() *InvoiceDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicedocument.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceDocument.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceDocumentUpsertBulk) Ignore() *InvoiceDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceDocumentUpsertBulk) DoNothing() *InvoiceDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceDocumentCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceDocumentUpsertBulk) Update(set func(*InvoiceDocumentUpsert)) *InvoiceDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetInvoiceRequestID sets the "invoice_request_id" field.
func (u *InvoiceDocumentUpsertBulk) SetInvoiceRequestID(v int64) *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetInvoiceRequestID(v)
	})
}

// AddInvoiceRequestID adds v to the "invoice_request_id" field.
func (u *InvoiceDocumentUpsertBulk) AddInvoiceRequestID(v int64) *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.AddInvoiceRequestID(v)
	})
}

// UpdateInvoiceRequestID sets the "invoice_request_id" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertBulk) UpdateInvoiceRequestID() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateInvoiceRequestID()
	})
}

// SetInvoiceNo sets the "invoice_no" field.
func (u *InvoiceDocumentUpsertBulk) SetInvoiceNo(v string) *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetInvoiceNo(v)
	})
}

// UpdateInvoiceNo sets the "invoice_no" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertBulk) UpdateInvoiceNo() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateInvoiceNo()
	})
}

// ClearInvoiceNo clears the value of the "invoice_no" field.
func (u *InvoiceDocumentUpsertBulk) ClearInvoiceNo() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearInvoiceNo()
	})
}

// SetInvoiceCode sets the "invoice_code" field.
func (u *InvoiceDocumentUpsertBulk) SetInvoiceCode(v string) *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetInvoiceCode(v)
	})
}

// UpdateInvoiceCode sets the "invoice_code" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertBulk) UpdateInvoiceCode() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateInvoiceCode()
	})
}

// ClearInvoiceCode clears the value of the "invoice_code" field.
func (u *InvoiceDocumentUpsertBulk) ClearInvoiceCode() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearInvoiceCode()
	})
}

// SetFileURL sets the "file_url" field.
func (u *InvoiceDocumentUpsertBulk) SetFileURL(v string) *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetFileURL(v)
	})
}

// UpdateFileURL sets the "file_url" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertBulk) UpdateFileURL() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateFileURL()
	})
}

// ClearFileURL clears the value of the "file_url" field.
func (u *InvoiceDocumentUpsertBulk) ClearFileURL() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearFileURL()
	})
}

// SetFileType sets the "file_type" field.
func (u *InvoiceDocumentUpsertBulk) SetFileType(v string) *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetFileType(v)
	})
}

// UpdateFileType sets the "file_type" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertBulk) UpdateFileType() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateFileType()
	})
}

// ClearFileType clears the value of the "file_type" field.
func (u *InvoiceDocumentUpsertBulk) ClearFileType() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearFileType()
	})
}

// SetRawPayloadSummary sets the "raw_payload_summary" field.
func (u *InvoiceDocumentUpsertBulk) SetRawPayloadSummary(v map[string]interface{}) *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.SetRawPayloadSummary(v)
	})
}

// UpdateRawPayloadSummary sets the "raw_payload_summary" field to the value that was provided on create.
func (u *InvoiceDocumentUpsertBulk) UpdateRawPayloadSummary() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.UpdateRawPayloadSummary()
	})
}

// ClearRawPayloadSummary clears the value of the "raw_payload_summary" field.
func (u *InvoiceDocumentUpsertBulk) ClearRawPayloadSummary() *InvoiceDocumentUpsertBulk {
	return u.Update(func(s *InvoiceDocumentUpsert) {
		s.ClearRawPayloadSummary()
	})
}

// Exec executes the query.
func (u *InvoiceDocumentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceDocumentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceDocumentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceDocumentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
