// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceprofile"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceProfileUpdate is the builder for updating InvoiceProfile entities.
type InvoiceProfileUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceProfileMutation
}

// Where appends a list predicates to the InvoiceProfileUpdate builder.
func (_u *InvoiceProfileUpdate) Where(ps ...predicate.InvoiceProfile) *InvoiceProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceProfileUpdate) SetUserID(v int64) *InvoiceProfileUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableUserID(v *int64) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *InvoiceProfileUpdate) AddUserID(v int64) *InvoiceProfileUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceProfileUpdate) SetTitle(v string) *InvoiceProfileUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableTitle(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxNo sets the "tax_no" field.
func (_u *InvoiceProfileUpdate) SetTaxNo(v string) *InvoiceProfileUpdate {
	_u.mutation.SetTaxNo(v)
	return _u
}

// SetNillableTaxNo sets the "tax_no" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableTaxNo(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetTaxNo(*v)
	}
	return _u
}

// ClearTaxNo clears the value of the "tax_no" field.
func (_u *InvoiceProfileUpdate) ClearTaxNo() *InvoiceProfileUpdate {
	_u.mutation.ClearTaxNo()
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceProfileUpdate) SetEmail(v string) *InvoiceProfileUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableEmail(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *InvoiceProfileUpdate) ClearEmail() *InvoiceProfileUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *InvoiceProfileUpdate) SetPhone(v string) *InvoiceProfileUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillablePhone(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *InvoiceProfileUpdate) ClearPhone() *InvoiceProfileUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetAddress sets the "address" field.
func (_u *InvoiceProfileUpdate) SetAddress(v string) *InvoiceProfileUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableAddress(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *InvoiceProfileUpdate) ClearAddress() *InvoiceProfileUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetBankName sets the "bank_name" field.
func (_u *InvoiceProfileUpdate) SetBankName(v string) *InvoiceProfileUpdate {
	_u.mutation.SetBankName(v)
	return _u
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableBankName(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetBankName(*v)
	}
	return _u
}

// ClearBankName clears the value of the "bank_name" field.
func (_u *InvoiceProfileUpdate) ClearBankName() *InvoiceProfileUpdate {
	_u.mutation.ClearBankName()
	return _u
}

// SetBankAccount sets the "bank_account" field.
func (_u *InvoiceProfileUpdate) SetBankAccount(v string) *InvoiceProfileUpdate {
	_u.mutation.SetBankAccount(v)
	return _u
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableBankAccount(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetBankAccount(*v)
	}
	return _u
}

// ClearBankAccount clears the value of the "bank_account" field.
func (_u *InvoiceProfileUpdate) ClearBankAccount() *InvoiceProfileUpdate {
	_u.mutation.ClearBankAccount()
	return _u
}

// SetInvoiceType sets the "invoice_type" field.
func (_u *InvoiceProfileUpdate) SetInvoiceType(v string) *InvoiceProfileUpdate {
	_u.mutation.SetInvoiceType(v)
	return _u
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableInvoiceType(v *string) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetInvoiceType(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *InvoiceProfileUpdate) SetIsDefault(v bool) *InvoiceProfileUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *InvoiceProfileUpdate) SetNillableIsDefault(v *bool) *InvoiceProfileUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceProfileUpdate) SetUpdatedAt(v time.Time) *InvoiceProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InvoiceProfileMutation object of the builder.
func (_u *InvoiceProfileUpdate) Mutation() *InvoiceProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceProfileUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := invoiceprofile.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNo(); ok {
		if err := invoiceprofile.TaxNoValidator(v); err != nil {
			return &ValidationError{Name: "tax_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.tax_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := invoiceprofile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := invoiceprofile.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankName(); ok {
		if err := invoiceprofile.BankNameValidator(v); err != nil {
			return &ValidationError{Name: "bank_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.bank_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankAccount(); ok {
		if err := invoiceprofile.BankAccountValidator(v); err != nil {
			return &ValidationError{Name: "bank_account", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.bank_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceType(); ok {
		if err := invoiceprofile.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.invoice_type": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceprofile.Table, invoiceprofile.Columns, sqlgraph.NewFieldSpec(invoiceprofile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(invoiceprofile.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(invoiceprofile.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoiceprofile.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNo(); ok {
		_spec.SetField(invoiceprofile.FieldTaxNo, field.TypeString, value)
	}
	if _u.mutation.TaxNoCleared() {
		_spec.ClearField(invoiceprofile.FieldTaxNo, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoiceprofile.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(invoiceprofile.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(invoiceprofile.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(invoiceprofile.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(invoiceprofile.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(invoiceprofile.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.BankName(); ok {
		_spec.SetField(invoiceprofile.FieldBankName, field.TypeString, value)
	}
	if _u.mutation.BankNameCleared() {
		_spec.ClearField(invoiceprofile.FieldBankName, field.TypeString)
	}
	if value, ok := _u.mutation.BankAccount(); ok {
		_spec.SetField(invoiceprofile.FieldBankAccount, field.TypeString, value)
	}
	if _u.mutation.BankAccountCleared() {
		_spec.ClearField(invoiceprofile.FieldBankAccount, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceType(); ok {
		_spec.SetField(invoiceprofile.FieldInvoiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(invoiceprofile.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceProfileUpdateOne is the builder for updating a single InvoiceProfile entity.
type InvoiceProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceProfileMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceProfileUpdateOne) SetUserID(v int64) *InvoiceProfileUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableUserID(v *int64) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *InvoiceProfileUpdateOne) AddUserID(v int64) *InvoiceProfileUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceProfileUpdateOne) SetTitle(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableTitle(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTaxNo sets the "tax_no" field.
func (_u *InvoiceProfileUpdateOne) SetTaxNo(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetTaxNo(v)
	return _u
}

// SetNillableTaxNo sets the "tax_no" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableTaxNo(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetTaxNo(*v)
	}
	return _u
}

// ClearTaxNo clears the value of the "tax_no" field.
func (_u *InvoiceProfileUpdateOne) ClearTaxNo() *InvoiceProfileUpdateOne {
	_u.mutation.ClearTaxNo()
	return _u
}

// SetEmail sets the "email" field.
func (_u *InvoiceProfileUpdateOne) SetEmail(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableEmail(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *InvoiceProfileUpdateOne) ClearEmail() *InvoiceProfileUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *InvoiceProfileUpdateOne) SetPhone(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillablePhone(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *InvoiceProfileUpdateOne) ClearPhone() *InvoiceProfileUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetAddress sets the "address" field.
func (_u *InvoiceProfileUpdateOne) SetAddress(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableAddress(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *InvoiceProfileUpdateOne) ClearAddress() *InvoiceProfileUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetBankName sets the "bank_name" field.
func (_u *InvoiceProfileUpdateOne) SetBankName(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetBankName(v)
	return _u
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableBankName(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetBankName(*v)
	}
	return _u
}

// ClearBankName clears the value of the "bank_name" field.
func (_u *InvoiceProfileUpdateOne) ClearBankName() *InvoiceProfileUpdateOne {
	_u.mutation.ClearBankName()
	return _u
}

// SetBankAccount sets the "bank_account" field.
func (_u *InvoiceProfileUpdateOne) SetBankAccount(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetBankAccount(v)
	return _u
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableBankAccount(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetBankAccount(*v)
	}
	return _u
}

// ClearBankAccount clears the value of the "bank_account" field.
func (_u *InvoiceProfileUpdateOne) ClearBankAccount() *InvoiceProfileUpdateOne {
	_u.mutation.ClearBankAccount()
	return _u
}

// SetInvoiceType sets the "invoice_type" field.
func (_u *InvoiceProfileUpdateOne) SetInvoiceType(v string) *InvoiceProfileUpdateOne {
	_u.mutation.SetInvoiceType(v)
	return _u
}

// SetNillableInvoiceType sets the "invoice_type" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableInvoiceType(v *string) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetInvoiceType(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *InvoiceProfileUpdateOne) SetIsDefault(v bool) *InvoiceProfileUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *InvoiceProfileUpdateOne) SetNillableIsDefault(v *bool) *InvoiceProfileUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceProfileUpdateOne) SetUpdatedAt(v time.Time) *InvoiceProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InvoiceProfileMutation object of the builder.
func (_u *InvoiceProfileUpdateOne) Mutation() *InvoiceProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the InvoiceProfileUpdate builder.
func (_u *InvoiceProfileUpdateOne) Where(ps ...predicate.InvoiceProfile) *InvoiceProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceProfileUpdateOne) Select(field string, fields ...string) *InvoiceProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceProfile entity.
func (_u *InvoiceProfileUpdateOne) Save(ctx context.Context) (*InvoiceProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceProfileUpdateOne) SaveX(ctx context.Context) *InvoiceProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := invoiceprofile.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxNo(); ok {
		if err := invoiceprofile.TaxNoValidator(v); err != nil {
			return &ValidationError{Name: "tax_no", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.tax_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := invoiceprofile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := invoiceprofile.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankName(); ok {
		if err := invoiceprofile.BankNameValidator(v); err != nil {
			return &ValidationError{Name: "bank_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.bank_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankAccount(); ok {
		if err := invoiceprofile.BankAccountValidator(v); err != nil {
			return &ValidationError{Name: "bank_account", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.bank_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceType(); ok {
		if err := invoiceprofile.InvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "invoice_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceProfile.invoice_type": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceProfileUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceprofile.Table, invoiceprofile.Columns, sqlgraph.NewFieldSpec(invoiceprofile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceprofile.FieldID)
		for _, f := range fields {
			if !invoiceprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(invoiceprofile.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(invoiceprofile.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoiceprofile.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxNo(); ok {
		_spec.SetField(invoiceprofile.FieldTaxNo, field.TypeString, value)
	}
	if _u.mutation.TaxNoCleared() {
		_spec.ClearField(invoiceprofile.FieldTaxNo, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(invoiceprofile.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(invoiceprofile.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(invoiceprofile.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(invoiceprofile.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(invoiceprofile.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(invoiceprofile.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.BankName(); ok {
		_spec.SetField(invoiceprofile.FieldBankName, field.TypeString, value)
	}
	if _u.mutation.BankNameCleared() {
		_spec.ClearField(invoiceprofile.FieldBankName, field.TypeString)
	}
	if value, ok := _u.mutation.BankAccount(); ok {
		_spec.SetField(invoiceprofile.FieldBankAccount, field.TypeString, value)
	}
	if _u.mutation.BankAccountCleared() {
		_spec.ClearField(invoiceprofile.FieldBankAccount, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceType(); ok {
		_spec.SetField(invoiceprofile.FieldInvoiceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(invoiceprofile.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &InvoiceProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
