// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceRequestUpdate is the builder for updating InvoiceRequest entities.
type InvoiceRequestUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceRequestMutation
}

// Where appends a list predicates to the InvoiceRequestUpdate builder.
func (_u *InvoiceRequestUpdate) Where(ps ...predicate.InvoiceRequest) *InvoiceRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceRequestUpdate) SetUserID(v int64) *InvoiceRequestUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableUserID(v *int64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *InvoiceRequestUpdate) AddUserID(v int64) *InvoiceRequestUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *InvoiceRequestUpdate) SetOrderID(v int64) *InvoiceRequestUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableOrderID(v *int64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *InvoiceRequestUpdate) AddOrderID(v int64) *InvoiceRequestUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *InvoiceRequestUpdate) SetProfileID(v int64) *InvoiceRequestUpdate {
	_u.mutation.ResetProfileID()
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableProfileID(v *int64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// AddProfileID adds value to the "profile_id" field.
func (_u *InvoiceRequestUpdate) AddProfileID(v int64) *InvoiceRequestUpdate {
	_u.mutation.AddProfileID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceRequestUpdate) SetStatus(v string) *InvoiceRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableStatus(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *InvoiceRequestUpdate) SetProvider(v string) *InvoiceRequestUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableProvider(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderRequestID sets the "provider_request_id" field.
func (_u *InvoiceRequestUpdate) SetProviderRequestID(v string) *InvoiceRequestUpdate {
	_u.mutation.SetProviderRequestID(v)
	return _u
}

// SetNillableProviderRequestID sets the "provider_request_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableProviderRequestID(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetProviderRequestID(*v)
	}
	return _u
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (_u *InvoiceRequestUpdate) ClearProviderRequestID() *InvoiceRequestUpdate {
	_u.mutation.ClearProviderRequestID()
	return _u
}

// SetProviderInvoiceID sets the "provider_invoice_id" field.
func (_u *InvoiceRequestUpdate) SetProviderInvoiceID(v string) *InvoiceRequestUpdate {
	_u.mutation.SetProviderInvoiceID(v)
	return _u
}

// SetNillableProviderInvoiceID sets the "provider_invoice_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableProviderInvoiceID(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetProviderInvoiceID(*v)
	}
	return _u
}

// ClearProviderInvoiceID clears the value of the "provider_invoice_id" field.
func (_u *InvoiceRequestUpdate) ClearProviderInvoiceID() *InvoiceRequestUpdate {
	_u.mutation.ClearProviderInvoiceID()
	return _u
}

// SetFailReason sets the "fail_reason" field.
func (_u *InvoiceRequestUpdate) SetFailReason(v string) *InvoiceRequestUpdate {
	_u.mutation.SetFailReason(v)
	return _u
}

// SetNillableFailReason sets the "fail_reason" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableFailReason(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetFailReason(*v)
	}
	return _u
}

// ClearFailReason clears the value of the "fail_reason" field.
func (_u *InvoiceRequestUpdate) ClearFailReason() *InvoiceRequestUpdate {
	_u.mutation.ClearFailReason()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *InvoiceRequestUpdate) SetRetryCount(v int) *InvoiceRequestUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableRetryCount(v *int) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *InvoiceRequestUpdate) AddRetryCount(v int) *InvoiceRequestUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *InvoiceRequestUpdate) SetRequestedAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableRequestedAt(v *time.Time) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceRequestUpdate) SetIssuedAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableIssuedAt(v *time.Time) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceRequestUpdate) ClearIssuedAt() *InvoiceRequestUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceRequestUpdate) SetUpdatedAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_u *InvoiceRequestUpdate) Mutation() *InvoiceRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoicerequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceRequestUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := invoicerequest.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderRequestID(); ok {
		if err := invoicerequest.ProviderRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_request_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.provider_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderInvoiceID(); ok {
		if err := invoicerequest.ProviderInvoiceIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_invoice_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.provider_invoice_id": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicerequest.Table, invoicerequest.Columns, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(invoicerequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(invoicerequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(invoicerequest.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(invoicerequest.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(invoicerequest.FieldProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProfileID(); ok {
		_spec.AddField(invoicerequest.FieldProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(invoicerequest.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderRequestID(); ok {
		_spec.SetField(invoicerequest.FieldProviderRequestID, field.TypeString, value)
	}
	if _u.mutation.ProviderRequestIDCleared() {
		_spec.ClearField(invoicerequest.FieldProviderRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderInvoiceID(); ok {
		_spec.SetField(invoicerequest.FieldProviderInvoiceID, field.TypeString, value)
	}
	if _u.mutation.ProviderInvoiceIDCleared() {
		_spec.ClearField(invoicerequest.FieldProviderInvoiceID, field.TypeString)
	}
	if value, ok := _u.mutation.FailReason(); ok {
		_spec.SetField(invoicerequest.FieldFailReason, field.TypeString, value)
	}
	if _u.mutation.FailReasonCleared() {
		_spec.ClearField(invoicerequest.FieldFailReason, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(invoicerequest.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(invoicerequest.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(invoicerequest.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceRequestUpdateOne is the builder for updating a single InvoiceRequest entity.
type InvoiceRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceRequestMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceRequestUpdateOne) SetUserID(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableUserID(v *int64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *InvoiceRequestUpdateOne) AddUserID(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *InvoiceRequestUpdateOne) SetOrderID(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableOrderID(v *int64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *InvoiceRequestUpdateOne) AddOrderID(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *InvoiceRequestUpdateOne) SetProfileID(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetProfileID()
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableProfileID(v *int64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// AddProfileID adds value to the "profile_id" field.
func (_u *InvoiceRequestUpdateOne) AddProfileID(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.AddProfileID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceRequestUpdateOne) SetStatus(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableStatus(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *InvoiceRequestUpdateOne) SetProvider(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableProvider(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderRequestID sets the "provider_request_id" field.
func (_u *InvoiceRequestUpdateOne) SetProviderRequestID(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetProviderRequestID(v)
	return _u
}

// SetNillableProviderRequestID sets the "provider_request_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableProviderRequestID(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetProviderRequestID(*v)
	}
	return _u
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (_u *InvoiceRequestUpdateOne) ClearProviderRequestID() *InvoiceRequestUpdateOne {
	_u.mutation.ClearProviderRequestID()
	return _u
}

// SetProviderInvoiceID sets the "provider_invoice_id" field.
func (_u *InvoiceRequestUpdateOne) SetProviderInvoiceID(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetProviderInvoiceID(v)
	return _u
}

// SetNillableProviderInvoiceID sets the "provider_invoice_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableProviderInvoiceID(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetProviderInvoiceID(*v)
	}
	return _u
}

// ClearProviderInvoiceID clears the value of the "provider_invoice_id" field.
func (_u *InvoiceRequestUpdateOne) ClearProviderInvoiceID() *InvoiceRequestUpdateOne {
	_u.mutation.ClearProviderInvoiceID()
	return _u
}

// SetFailReason sets the "fail_reason" field.
func (_u *InvoiceRequestUpdateOne) SetFailReason(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetFailReason(v)
	return _u
}

// SetNillableFailReason sets the "fail_reason" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableFailReason(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetFailReason(*v)
	}
	return _u
}

// ClearFailReason clears the value of the "fail_reason" field.
func (_u *InvoiceRequestUpdateOne) ClearFailReason() *InvoiceRequestUpdateOne {
	_u.mutation.ClearFailReason()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *InvoiceRequestUpdateOne) SetRetryCount(v int) *InvoiceRequestUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableRetryCount(v *int) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *InvoiceRequestUpdateOne) AddRetryCount(v int) *InvoiceRequestUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *InvoiceRequestUpdateOne) SetRequestedAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableRequestedAt(v *time.Time) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceRequestUpdateOne) SetIssuedAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableIssuedAt(v *time.Time) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceRequestUpdateOne) ClearIssuedAt() *InvoiceRequestUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceRequestUpdateOne) SetUpdatedAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_u *InvoiceRequestUpdateOne) Mutation() *InvoiceRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the InvoiceRequestUpdate builder.
func (_u *InvoiceRequestUpdateOne) Where(ps ...predicate.InvoiceRequest) *InvoiceRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceRequestUpdateOne) Select(field string, fields ...string) *InvoiceRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceRequest entity.
func (_u *InvoiceRequestUpdateOne) Save(ctx context.Context) (*InvoiceRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestUpdateOne) SaveX(ctx context.Context) *InvoiceRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoicerequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := invoicerequest.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderRequestID(); ok {
		if err := invoicerequest.ProviderRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_request_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.provider_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderInvoiceID(); ok {
		if err := invoicerequest.ProviderInvoiceIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_invoice_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.provider_invoice_id": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceRequestUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicerequest.Table, invoicerequest.Columns, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicerequest.FieldID)
		for _, f := range fields {
			if !invoicerequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoicerequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(invoicerequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(invoicerequest.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(invoicerequest.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(invoicerequest.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProfileID(); ok {
		_spec.SetField(invoicerequest.FieldProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProfileID(); ok {
		_spec.AddField(invoicerequest.FieldProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(invoicerequest.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderRequestID(); ok {
		_spec.SetField(invoicerequest.FieldProviderRequestID, field.TypeString, value)
	}
	if _u.mutation.ProviderRequestIDCleared() {
		_spec.ClearField(invoicerequest.FieldProviderRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderInvoiceID(); ok {
		_spec.SetField(invoicerequest.FieldProviderInvoiceID, field.TypeString, value)
	}
	if _u.mutation.ProviderInvoiceIDCleared() {
		_spec.ClearField(invoicerequest.FieldProviderInvoiceID, field.TypeString)
	}
	if value, ok := _u.mutation.FailReason(); ok {
		_spec.SetField(invoicerequest.FieldFailReason, field.TypeString, value)
	}
	if _u.mutation.FailReasonCleared() {
		_spec.ClearField(invoicerequest.FieldFailReason, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(invoicerequest.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(invoicerequest.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(invoicerequest.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &InvoiceRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
