// Code generated by ent, DO NOT EDIT.

package invoicerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoicerequest type in the database.
	Label = "invoice_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProfileID holds the string denoting the profile_id field in the database.
	FieldProfileID = "profile_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPaidTotal holds the string denoting the paid_total field in the database.
	FieldPaidTotal = "paid_total"
	// FieldInvoicedTotal holds the string denoting the invoiced_total field in the database.
	FieldInvoicedTotal = "invoiced_total"
	// FieldReservedTotal holds the string denoting the reserved_total field in the database.
	FieldReservedTotal = "reserved_total"
	// FieldAvailableAmount holds the string denoting the available_amount field in the database.
	FieldAvailableAmount = "available_amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldTitleType holds the string denoting the title_type field in the database.
	FieldTitleType = "title_type"
	// FieldTitleName holds the string denoting the title_name field in the database.
	FieldTitleName = "title_name"
	// FieldTaxNo holds the string denoting the tax_no field in the database.
	FieldTaxNo = "tax_no"
	// FieldAddressPhone holds the string denoting the address_phone field in the database.
	FieldAddressPhone = "address_phone"
	// FieldBankAccount holds the string denoting the bank_account field in the database.
	FieldBankAccount = "bank_account"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldSdkCode holds the string denoting the sdk_code field in the database.
	FieldSdkCode = "sdk_code"
	// FieldSdkMessage holds the string denoting the sdk_message field in the database.
	FieldSdkMessage = "sdk_message"
	// FieldSdkResponse holds the string denoting the sdk_response field in the database.
	FieldSdkResponse = "sdk_response"
	// FieldInvoiceNo holds the string denoting the invoice_no field in the database.
	FieldInvoiceNo = "invoice_no"
	// FieldInvoiceDate holds the string denoting the invoice_date field in the database.
	FieldInvoiceDate = "invoice_date"
	// FieldPdfURL holds the string denoting the pdf_url field in the database.
	FieldPdfURL = "pdf_url"
	// FieldOfdURL holds the string denoting the ofd_url field in the database.
	FieldOfdURL = "ofd_url"
	// FieldXMLURL holds the string denoting the xml_url field in the database.
	FieldXMLURL = "xml_url"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the invoicerequest in the database.
	Table = "invoice_requests"
)

// Columns holds all SQL columns for invoicerequest fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldProfileID,
	FieldStatus,
	FieldAmount,
	FieldPaidTotal,
	FieldInvoicedTotal,
	FieldReservedTotal,
	FieldAvailableAmount,
	FieldCurrency,
	FieldTitleType,
	FieldTitleName,
	FieldTaxNo,
	FieldAddressPhone,
	FieldBankAccount,
	FieldEmail,
	FieldContent,
	FieldRemark,
	FieldSdkCode,
	FieldSdkMessage,
	FieldSdkResponse,
	FieldInvoiceNo,
	FieldInvoiceDate,
	FieldPdfURL,
	FieldOfdURL,
	FieldXMLURL,
	FieldIssuedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultPaidTotal holds the default value on creation for the "paid_total" field.
	DefaultPaidTotal float64
	// DefaultInvoicedTotal holds the default value on creation for the "invoiced_total" field.
	DefaultInvoicedTotal float64
	// DefaultReservedTotal holds the default value on creation for the "reserved_total" field.
	DefaultReservedTotal float64
	// DefaultAvailableAmount holds the default value on creation for the "available_amount" field.
	DefaultAvailableAmount float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultTitleType holds the default value on creation for the "title_type" field.
	DefaultTitleType string
	// TitleTypeValidator is a validator for the "title_type" field. It is called by the builders before save.
	TitleTypeValidator func(string) error
	// TitleNameValidator is a validator for the "title_name" field. It is called by the builders before save.
	TitleNameValidator func(string) error
	// DefaultTaxNo holds the default value on creation for the "tax_no" field.
	DefaultTaxNo string
	// TaxNoValidator is a validator for the "tax_no" field. It is called by the builders before save.
	TaxNoValidator func(string) error
	// DefaultAddressPhone holds the default value on creation for the "address_phone" field.
	DefaultAddressPhone string
	// DefaultBankAccount holds the default value on creation for the "bank_account" field.
	DefaultBankAccount string
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultRemark holds the default value on creation for the "remark" field.
	DefaultRemark string
	// DefaultSdkMessage holds the default value on creation for the "sdk_message" field.
	DefaultSdkMessage string
	// DefaultInvoiceNo holds the default value on creation for the "invoice_no" field.
	DefaultInvoiceNo string
	// InvoiceNoValidator is a validator for the "invoice_no" field. It is called by the builders before save.
	InvoiceNoValidator func(string) error
	// DefaultInvoiceDate holds the default value on creation for the "invoice_date" field.
	DefaultInvoiceDate string
	// InvoiceDateValidator is a validator for the "invoice_date" field. It is called by the builders before save.
	InvoiceDateValidator func(string) error
	// DefaultPdfURL holds the default value on creation for the "pdf_url" field.
	DefaultPdfURL string
	// DefaultOfdURL holds the default value on creation for the "ofd_url" field.
	DefaultOfdURL string
	// DefaultXMLURL holds the default value on creation for the "xml_url" field.
	DefaultXMLURL string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByProfileID orders the results by the profile_id field.
func ByProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByPaidTotal orders the results by the paid_total field.
func ByPaidTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidTotal, opts...).ToFunc()
}

// ByInvoicedTotal orders the results by the invoiced_total field.
func ByInvoicedTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoicedTotal, opts...).ToFunc()
}

// ByReservedTotal orders the results by the reserved_total field.
func ByReservedTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedTotal, opts...).ToFunc()
}

// ByAvailableAmount orders the results by the available_amount field.
func ByAvailableAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByTitleType orders the results by the title_type field.
func ByTitleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleType, opts...).ToFunc()
}

// ByTitleName orders the results by the title_name field.
func ByTitleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleName, opts...).ToFunc()
}

// ByTaxNo orders the results by the tax_no field.
func ByTaxNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxNo, opts...).ToFunc()
}

// ByAddressPhone orders the results by the address_phone field.
func ByAddressPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddressPhone, opts...).ToFunc()
}

// ByBankAccount orders the results by the bank_account field.
func ByBankAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankAccount, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// BySdkCode orders the results by the sdk_code field.
func BySdkCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSdkCode, opts...).ToFunc()
}

// BySdkMessage orders the results by the sdk_message field.
func BySdkMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSdkMessage, opts...).ToFunc()
}

// ByInvoiceNo orders the results by the invoice_no field.
func ByInvoiceNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceNo, opts...).ToFunc()
}

// ByInvoiceDate orders the results by the invoice_date field.
func ByInvoiceDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceDate, opts...).ToFunc()
}

// ByPdfURL orders the results by the pdf_url field.
func ByPdfURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPdfURL, opts...).ToFunc()
}

// ByOfdURL orders the results by the ofd_url field.
func ByOfdURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfdURL, opts...).ToFunc()
}

// ByXMLURL orders the results by the xml_url field.
func ByXMLURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldXMLURL, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
