// Code generated by ent, DO NOT EDIT.

package invoicerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserID, v))
}

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldProfileID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldStatus, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAmount, v))
}

// PaidTotal applies equality check predicate on the "paid_total" field. It's identical to PaidTotalEQ.
func PaidTotal(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldPaidTotal, v))
}

// InvoicedTotal applies equality check predicate on the "invoiced_total" field. It's identical to InvoicedTotalEQ.
func InvoicedTotal(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoicedTotal, v))
}

// ReservedTotal applies equality check predicate on the "reserved_total" field. It's identical to ReservedTotalEQ.
func ReservedTotal(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldReservedTotal, v))
}

// AvailableAmount applies equality check predicate on the "available_amount" field. It's identical to AvailableAmountEQ.
func AvailableAmount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAvailableAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCurrency, v))
}

// TitleType applies equality check predicate on the "title_type" field. It's identical to TitleTypeEQ.
func TitleType(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitleType, v))
}

// TitleName applies equality check predicate on the "title_name" field. It's identical to TitleNameEQ.
func TitleName(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitleName, v))
}

// TaxNo applies equality check predicate on the "tax_no" field. It's identical to TaxNoEQ.
func TaxNo(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxNo, v))
}

// AddressPhone applies equality check predicate on the "address_phone" field. It's identical to AddressPhoneEQ.
func AddressPhone(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAddressPhone, v))
}

// BankAccount applies equality check predicate on the "bank_account" field. It's identical to BankAccountEQ.
func BankAccount(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldBankAccount, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldEmail, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldContent, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRemark, v))
}

// SdkCode applies equality check predicate on the "sdk_code" field. It's identical to SdkCodeEQ.
func SdkCode(v int) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldSdkCode, v))
}

// SdkMessage applies equality check predicate on the "sdk_message" field. It's identical to SdkMessageEQ.
func SdkMessage(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldSdkMessage, v))
}

// InvoiceNo applies equality check predicate on the "invoice_no" field. It's identical to InvoiceNoEQ.
func InvoiceNo(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceDate applies equality check predicate on the "invoice_date" field. It's identical to InvoiceDateEQ.
func InvoiceDate(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceDate, v))
}

// PdfURL applies equality check predicate on the "pdf_url" field. It's identical to PdfURLEQ.
func PdfURL(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldPdfURL, v))
}

// OfdURL applies equality check predicate on the "ofd_url" field. It's identical to OfdURLEQ.
func OfdURL(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldOfdURL, v))
}

// XMLURL applies equality check predicate on the "xml_url" field. It's identical to XMLURLEQ.
func XMLURL(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldXMLURL, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldUserID, v))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldProfileID, vs...))
}

// ProfileIDGT applies the GT predicate on the "profile_id" field.
func ProfileIDGT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldProfileID, v))
}

// ProfileIDGTE applies the GTE predicate on the "profile_id" field.
func ProfileIDGTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldProfileID, v))
}

// ProfileIDLT applies the LT predicate on the "profile_id" field.
func ProfileIDLT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldProfileID, v))
}

// ProfileIDLTE applies the LTE predicate on the "profile_id" field.
func ProfileIDLTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldProfileID, v))
}

// ProfileIDIsNil applies the IsNil predicate on the "profile_id" field.
func ProfileIDIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldProfileID))
}

// ProfileIDNotNil applies the NotNil predicate on the "profile_id" field.
func ProfileIDNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldProfileID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldStatus, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldAmount, v))
}

// PaidTotalEQ applies the EQ predicate on the "paid_total" field.
func PaidTotalEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldPaidTotal, v))
}

// PaidTotalNEQ applies the NEQ predicate on the "paid_total" field.
func PaidTotalNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldPaidTotal, v))
}

// PaidTotalIn applies the In predicate on the "paid_total" field.
func PaidTotalIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldPaidTotal, vs...))
}

// PaidTotalNotIn applies the NotIn predicate on the "paid_total" field.
func PaidTotalNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldPaidTotal, vs...))
}

// PaidTotalGT applies the GT predicate on the "paid_total" field.
func PaidTotalGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldPaidTotal, v))
}

// PaidTotalGTE applies the GTE predicate on the "paid_total" field.
func PaidTotalGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldPaidTotal, v))
}

// PaidTotalLT applies the LT predicate on the "paid_total" field.
func PaidTotalLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldPaidTotal, v))
}

// PaidTotalLTE applies the LTE predicate on the "paid_total" field.
func PaidTotalLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldPaidTotal, v))
}

// InvoicedTotalEQ applies the EQ predicate on the "invoiced_total" field.
func InvoicedTotalEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoicedTotal, v))
}

// InvoicedTotalNEQ applies the NEQ predicate on the "invoiced_total" field.
func InvoicedTotalNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldInvoicedTotal, v))
}

// InvoicedTotalIn applies the In predicate on the "invoiced_total" field.
func InvoicedTotalIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldInvoicedTotal, vs...))
}

// InvoicedTotalNotIn applies the NotIn predicate on the "invoiced_total" field.
func InvoicedTotalNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldInvoicedTotal, vs...))
}

// InvoicedTotalGT applies the GT predicate on the "invoiced_total" field.
func InvoicedTotalGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldInvoicedTotal, v))
}

// InvoicedTotalGTE applies the GTE predicate on the "invoiced_total" field.
func InvoicedTotalGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldInvoicedTotal, v))
}

// InvoicedTotalLT applies the LT predicate on the "invoiced_total" field.
func InvoicedTotalLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldInvoicedTotal, v))
}

// InvoicedTotalLTE applies the LTE predicate on the "invoiced_total" field.
func InvoicedTotalLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldInvoicedTotal, v))
}

// ReservedTotalEQ applies the EQ predicate on the "reserved_total" field.
func ReservedTotalEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldReservedTotal, v))
}

// ReservedTotalNEQ applies the NEQ predicate on the "reserved_total" field.
func ReservedTotalNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldReservedTotal, v))
}

// ReservedTotalIn applies the In predicate on the "reserved_total" field.
func ReservedTotalIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldReservedTotal, vs...))
}

// ReservedTotalNotIn applies the NotIn predicate on the "reserved_total" field.
func ReservedTotalNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldReservedTotal, vs...))
}

// ReservedTotalGT applies the GT predicate on the "reserved_total" field.
func ReservedTotalGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldReservedTotal, v))
}

// ReservedTotalGTE applies the GTE predicate on the "reserved_total" field.
func ReservedTotalGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldReservedTotal, v))
}

// ReservedTotalLT applies the LT predicate on the "reserved_total" field.
func ReservedTotalLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldReservedTotal, v))
}

// ReservedTotalLTE applies the LTE predicate on the "reserved_total" field.
func ReservedTotalLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldReservedTotal, v))
}

// AvailableAmountEQ applies the EQ predicate on the "available_amount" field.
func AvailableAmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAvailableAmount, v))
}

// AvailableAmountNEQ applies the NEQ predicate on the "available_amount" field.
func AvailableAmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldAvailableAmount, v))
}

// AvailableAmountIn applies the In predicate on the "available_amount" field.
func AvailableAmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldAvailableAmount, vs...))
}

// AvailableAmountNotIn applies the NotIn predicate on the "available_amount" field.
func AvailableAmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldAvailableAmount, vs...))
}

// AvailableAmountGT applies the GT predicate on the "available_amount" field.
func AvailableAmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldAvailableAmount, v))
}

// AvailableAmountGTE applies the GTE predicate on the "available_amount" field.
func AvailableAmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldAvailableAmount, v))
}

// AvailableAmountLT applies the LT predicate on the "available_amount" field.
func AvailableAmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldAvailableAmount, v))
}

// AvailableAmountLTE applies the LTE predicate on the "available_amount" field.
func AvailableAmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldAvailableAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldCurrency, v))
}

// TitleTypeEQ applies the EQ predicate on the "title_type" field.
func TitleTypeEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitleType, v))
}

// TitleTypeNEQ applies the NEQ predicate on the "title_type" field.
func TitleTypeNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTitleType, v))
}

// TitleTypeIn applies the In predicate on the "title_type" field.
func TitleTypeIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTitleType, vs...))
}

// TitleTypeNotIn applies the NotIn predicate on the "title_type" field.
func TitleTypeNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTitleType, vs...))
}

// TitleTypeGT applies the GT predicate on the "title_type" field.
func TitleTypeGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTitleType, v))
}

// TitleTypeGTE applies the GTE predicate on the "title_type" field.
func TitleTypeGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTitleType, v))
}

// TitleTypeLT applies the LT predicate on the "title_type" field.
func TitleTypeLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTitleType, v))
}

// TitleTypeLTE applies the LTE predicate on the "title_type" field.
func TitleTypeLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTitleType, v))
}

// TitleTypeContains applies the Contains predicate on the "title_type" field.
func TitleTypeContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTitleType, v))
}

// TitleTypeHasPrefix applies the HasPrefix predicate on the "title_type" field.
func TitleTypeHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTitleType, v))
}

// TitleTypeHasSuffix applies the HasSuffix predicate on the "title_type" field.
func TitleTypeHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTitleType, v))
}

// TitleTypeEqualFold applies the EqualFold predicate on the "title_type" field.
func TitleTypeEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTitleType, v))
}

// TitleTypeContainsFold applies the ContainsFold predicate on the "title_type" field.
func TitleTypeContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTitleType, v))
}

// TitleNameEQ applies the EQ predicate on the "title_name" field.
func TitleNameEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitleName, v))
}

// TitleNameNEQ applies the NEQ predicate on the "title_name" field.
func TitleNameNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTitleName, v))
}

// TitleNameIn applies the In predicate on the "title_name" field.
func TitleNameIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTitleName, vs...))
}

// TitleNameNotIn applies the NotIn predicate on the "title_name" field.
func TitleNameNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTitleName, vs...))
}

// TitleNameGT applies the GT predicate on the "title_name" field.
func TitleNameGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTitleName, v))
}

// TitleNameGTE applies the GTE predicate on the "title_name" field.
func TitleNameGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTitleName, v))
}

// TitleNameLT applies the LT predicate on the "title_name" field.
func TitleNameLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTitleName, v))
}

// TitleNameLTE applies the LTE predicate on the "title_name" field.
func TitleNameLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTitleName, v))
}

// TitleNameContains applies the Contains predicate on the "title_name" field.
func TitleNameContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTitleName, v))
}

// TitleNameHasPrefix applies the HasPrefix predicate on the "title_name" field.
func TitleNameHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTitleName, v))
}

// TitleNameHasSuffix applies the HasSuffix predicate on the "title_name" field.
func TitleNameHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTitleName, v))
}

// TitleNameEqualFold applies the EqualFold predicate on the "title_name" field.
func TitleNameEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTitleName, v))
}

// TitleNameContainsFold applies the ContainsFold predicate on the "title_name" field.
func TitleNameContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTitleName, v))
}

// TaxNoEQ applies the EQ predicate on the "tax_no" field.
func TaxNoEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxNo, v))
}

// TaxNoNEQ applies the NEQ predicate on the "tax_no" field.
func TaxNoNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTaxNo, v))
}

// TaxNoIn applies the In predicate on the "tax_no" field.
func TaxNoIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTaxNo, vs...))
}

// TaxNoNotIn applies the NotIn predicate on the "tax_no" field.
func TaxNoNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTaxNo, vs...))
}

// TaxNoGT applies the GT predicate on the "tax_no" field.
func TaxNoGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTaxNo, v))
}

// TaxNoGTE applies the GTE predicate on the "tax_no" field.
func TaxNoGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTaxNo, v))
}

// TaxNoLT applies the LT predicate on the "tax_no" field.
func TaxNoLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTaxNo, v))
}

// TaxNoLTE applies the LTE predicate on the "tax_no" field.
func TaxNoLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTaxNo, v))
}

// TaxNoContains applies the Contains predicate on the "tax_no" field.
func TaxNoContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTaxNo, v))
}

// TaxNoHasPrefix applies the HasPrefix predicate on the "tax_no" field.
func TaxNoHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTaxNo, v))
}

// TaxNoHasSuffix applies the HasSuffix predicate on the "tax_no" field.
func TaxNoHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTaxNo, v))
}

// TaxNoEqualFold applies the EqualFold predicate on the "tax_no" field.
func TaxNoEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTaxNo, v))
}

// TaxNoContainsFold applies the ContainsFold predicate on the "tax_no" field.
func TaxNoContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTaxNo, v))
}

// AddressPhoneEQ applies the EQ predicate on the "address_phone" field.
func AddressPhoneEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAddressPhone, v))
}

// AddressPhoneNEQ applies the NEQ predicate on the "address_phone" field.
func AddressPhoneNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldAddressPhone, v))
}

// AddressPhoneIn applies the In predicate on the "address_phone" field.
func AddressPhoneIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldAddressPhone, vs...))
}

// AddressPhoneNotIn applies the NotIn predicate on the "address_phone" field.
func AddressPhoneNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldAddressPhone, vs...))
}

// AddressPhoneGT applies the GT predicate on the "address_phone" field.
func AddressPhoneGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldAddressPhone, v))
}

// AddressPhoneGTE applies the GTE predicate on the "address_phone" field.
func AddressPhoneGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldAddressPhone, v))
}

// AddressPhoneLT applies the LT predicate on the "address_phone" field.
func AddressPhoneLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldAddressPhone, v))
}

// AddressPhoneLTE applies the LTE predicate on the "address_phone" field.
func AddressPhoneLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldAddressPhone, v))
}

// AddressPhoneContains applies the Contains predicate on the "address_phone" field.
func AddressPhoneContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldAddressPhone, v))
}

// AddressPhoneHasPrefix applies the HasPrefix predicate on the "address_phone" field.
func AddressPhoneHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldAddressPhone, v))
}

// AddressPhoneHasSuffix applies the HasSuffix predicate on the "address_phone" field.
func AddressPhoneHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldAddressPhone, v))
}

// AddressPhoneEqualFold applies the EqualFold predicate on the "address_phone" field.
func AddressPhoneEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldAddressPhone, v))
}

// AddressPhoneContainsFold applies the ContainsFold predicate on the "address_phone" field.
func AddressPhoneContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldAddressPhone, v))
}

// BankAccountEQ applies the EQ predicate on the "bank_account" field.
func BankAccountEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldBankAccount, v))
}

// BankAccountNEQ applies the NEQ predicate on the "bank_account" field.
func BankAccountNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldBankAccount, v))
}

// BankAccountIn applies the In predicate on the "bank_account" field.
func BankAccountIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldBankAccount, vs...))
}

// BankAccountNotIn applies the NotIn predicate on the "bank_account" field.
func BankAccountNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldBankAccount, vs...))
}

// BankAccountGT applies the GT predicate on the "bank_account" field.
func BankAccountGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldBankAccount, v))
}

// BankAccountGTE applies the GTE predicate on the "bank_account" field.
func BankAccountGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldBankAccount, v))
}

// BankAccountLT applies the LT predicate on the "bank_account" field.
func BankAccountLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldBankAccount, v))
}

// BankAccountLTE applies the LTE predicate on the "bank_account" field.
func BankAccountLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldBankAccount, v))
}

// BankAccountContains applies the Contains predicate on the "bank_account" field.
func BankAccountContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldBankAccount, v))
}

// BankAccountHasPrefix applies the HasPrefix predicate on the "bank_account" field.
func BankAccountHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldBankAccount, v))
}

// BankAccountHasSuffix applies the HasSuffix predicate on the "bank_account" field.
func BankAccountHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldBankAccount, v))
}

// BankAccountEqualFold applies the EqualFold predicate on the "bank_account" field.
func BankAccountEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldBankAccount, v))
}

// BankAccountContainsFold applies the ContainsFold predicate on the "bank_account" field.
func BankAccountContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldBankAccount, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldEmail, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldContent, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldRemark, v))
}

// SdkCodeEQ applies the EQ predicate on the "sdk_code" field.
func SdkCodeEQ(v int) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldSdkCode, v))
}

// SdkCodeNEQ applies the NEQ predicate on the "sdk_code" field.
func SdkCodeNEQ(v int) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldSdkCode, v))
}

// SdkCodeIn applies the In predicate on the "sdk_code" field.
func SdkCodeIn(vs ...int) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldSdkCode, vs...))
}

// SdkCodeNotIn applies the NotIn predicate on the "sdk_code" field.
func SdkCodeNotIn(vs ...int) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldSdkCode, vs...))
}

// SdkCodeGT applies the GT predicate on the "sdk_code" field.
func SdkCodeGT(v int) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldSdkCode, v))
}

// SdkCodeGTE applies the GTE predicate on the "sdk_code" field.
func SdkCodeGTE(v int) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldSdkCode, v))
}

// SdkCodeLT applies the LT predicate on the "sdk_code" field.
func SdkCodeLT(v int) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldSdkCode, v))
}

// SdkCodeLTE applies the LTE predicate on the "sdk_code" field.
func SdkCodeLTE(v int) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldSdkCode, v))
}

// SdkCodeIsNil applies the IsNil predicate on the "sdk_code" field.
func SdkCodeIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldSdkCode))
}

// SdkCodeNotNil applies the NotNil predicate on the "sdk_code" field.
func SdkCodeNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldSdkCode))
}

// SdkMessageEQ applies the EQ predicate on the "sdk_message" field.
func SdkMessageEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldSdkMessage, v))
}

// SdkMessageNEQ applies the NEQ predicate on the "sdk_message" field.
func SdkMessageNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldSdkMessage, v))
}

// SdkMessageIn applies the In predicate on the "sdk_message" field.
func SdkMessageIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldSdkMessage, vs...))
}

// SdkMessageNotIn applies the NotIn predicate on the "sdk_message" field.
func SdkMessageNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldSdkMessage, vs...))
}

// SdkMessageGT applies the GT predicate on the "sdk_message" field.
func SdkMessageGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldSdkMessage, v))
}

// SdkMessageGTE applies the GTE predicate on the "sdk_message" field.
func SdkMessageGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldSdkMessage, v))
}

// SdkMessageLT applies the LT predicate on the "sdk_message" field.
func SdkMessageLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldSdkMessage, v))
}

// SdkMessageLTE applies the LTE predicate on the "sdk_message" field.
func SdkMessageLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldSdkMessage, v))
}

// SdkMessageContains applies the Contains predicate on the "sdk_message" field.
func SdkMessageContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldSdkMessage, v))
}

// SdkMessageHasPrefix applies the HasPrefix predicate on the "sdk_message" field.
func SdkMessageHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldSdkMessage, v))
}

// SdkMessageHasSuffix applies the HasSuffix predicate on the "sdk_message" field.
func SdkMessageHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldSdkMessage, v))
}

// SdkMessageEqualFold applies the EqualFold predicate on the "sdk_message" field.
func SdkMessageEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldSdkMessage, v))
}

// SdkMessageContainsFold applies the ContainsFold predicate on the "sdk_message" field.
func SdkMessageContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldSdkMessage, v))
}

// SdkResponseIsNil applies the IsNil predicate on the "sdk_response" field.
func SdkResponseIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldSdkResponse))
}

// SdkResponseNotNil applies the NotNil predicate on the "sdk_response" field.
func SdkResponseNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldSdkResponse))
}

// InvoiceNoEQ applies the EQ predicate on the "invoice_no" field.
func InvoiceNoEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceNo, v))
}

// InvoiceNoNEQ applies the NEQ predicate on the "invoice_no" field.
func InvoiceNoNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldInvoiceNo, v))
}

// InvoiceNoIn applies the In predicate on the "invoice_no" field.
func InvoiceNoIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldInvoiceNo, vs...))
}

// InvoiceNoNotIn applies the NotIn predicate on the "invoice_no" field.
func InvoiceNoNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldInvoiceNo, vs...))
}

// InvoiceNoGT applies the GT predicate on the "invoice_no" field.
func InvoiceNoGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldInvoiceNo, v))
}

// InvoiceNoGTE applies the GTE predicate on the "invoice_no" field.
func InvoiceNoGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldInvoiceNo, v))
}

// InvoiceNoLT applies the LT predicate on the "invoice_no" field.
func InvoiceNoLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldInvoiceNo, v))
}

// InvoiceNoLTE applies the LTE predicate on the "invoice_no" field.
func InvoiceNoLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldInvoiceNo, v))
}

// InvoiceNoContains applies the Contains predicate on the "invoice_no" field.
func InvoiceNoContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldInvoiceNo, v))
}

// InvoiceNoHasPrefix applies the HasPrefix predicate on the "invoice_no" field.
func InvoiceNoHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldInvoiceNo, v))
}

// InvoiceNoHasSuffix applies the HasSuffix predicate on the "invoice_no" field.
func InvoiceNoHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldInvoiceNo, v))
}

// InvoiceNoEqualFold applies the EqualFold predicate on the "invoice_no" field.
func InvoiceNoEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldInvoiceNo, v))
}

// InvoiceNoContainsFold applies the ContainsFold predicate on the "invoice_no" field.
func InvoiceNoContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldInvoiceNo, v))
}

// InvoiceDateEQ applies the EQ predicate on the "invoice_date" field.
func InvoiceDateEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceDate, v))
}

// InvoiceDateNEQ applies the NEQ predicate on the "invoice_date" field.
func InvoiceDateNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldInvoiceDate, v))
}

// InvoiceDateIn applies the In predicate on the "invoice_date" field.
func InvoiceDateIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldInvoiceDate, vs...))
}

// InvoiceDateNotIn applies the NotIn predicate on the "invoice_date" field.
func InvoiceDateNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldInvoiceDate, vs...))
}

// InvoiceDateGT applies the GT predicate on the "invoice_date" field.
func InvoiceDateGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldInvoiceDate, v))
}

// InvoiceDateGTE applies the GTE predicate on the "invoice_date" field.
func InvoiceDateGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldInvoiceDate, v))
}

// InvoiceDateLT applies the LT predicate on the "invoice_date" field.
func InvoiceDateLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldInvoiceDate, v))
}

// InvoiceDateLTE applies the LTE predicate on the "invoice_date" field.
func InvoiceDateLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldInvoiceDate, v))
}

// InvoiceDateContains applies the Contains predicate on the "invoice_date" field.
func InvoiceDateContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldInvoiceDate, v))
}

// InvoiceDateHasPrefix applies the HasPrefix predicate on the "invoice_date" field.
func InvoiceDateHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldInvoiceDate, v))
}

// InvoiceDateHasSuffix applies the HasSuffix predicate on the "invoice_date" field.
func InvoiceDateHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldInvoiceDate, v))
}

// InvoiceDateEqualFold applies the EqualFold predicate on the "invoice_date" field.
func InvoiceDateEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldInvoiceDate, v))
}

// InvoiceDateContainsFold applies the ContainsFold predicate on the "invoice_date" field.
func InvoiceDateContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldInvoiceDate, v))
}

// PdfURLEQ applies the EQ predicate on the "pdf_url" field.
func PdfURLEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldPdfURL, v))
}

// PdfURLNEQ applies the NEQ predicate on the "pdf_url" field.
func PdfURLNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldPdfURL, v))
}

// PdfURLIn applies the In predicate on the "pdf_url" field.
func PdfURLIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldPdfURL, vs...))
}

// PdfURLNotIn applies the NotIn predicate on the "pdf_url" field.
func PdfURLNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldPdfURL, vs...))
}

// PdfURLGT applies the GT predicate on the "pdf_url" field.
func PdfURLGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldPdfURL, v))
}

// PdfURLGTE applies the GTE predicate on the "pdf_url" field.
func PdfURLGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldPdfURL, v))
}

// PdfURLLT applies the LT predicate on the "pdf_url" field.
func PdfURLLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldPdfURL, v))
}

// PdfURLLTE applies the LTE predicate on the "pdf_url" field.
func PdfURLLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldPdfURL, v))
}

// PdfURLContains applies the Contains predicate on the "pdf_url" field.
func PdfURLContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldPdfURL, v))
}

// PdfURLHasPrefix applies the HasPrefix predicate on the "pdf_url" field.
func PdfURLHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldPdfURL, v))
}

// PdfURLHasSuffix applies the HasSuffix predicate on the "pdf_url" field.
func PdfURLHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldPdfURL, v))
}

// PdfURLEqualFold applies the EqualFold predicate on the "pdf_url" field.
func PdfURLEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldPdfURL, v))
}

// PdfURLContainsFold applies the ContainsFold predicate on the "pdf_url" field.
func PdfURLContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldPdfURL, v))
}

// OfdURLEQ applies the EQ predicate on the "ofd_url" field.
func OfdURLEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldOfdURL, v))
}

// OfdURLNEQ applies the NEQ predicate on the "ofd_url" field.
func OfdURLNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldOfdURL, v))
}

// OfdURLIn applies the In predicate on the "ofd_url" field.
func OfdURLIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldOfdURL, vs...))
}

// OfdURLNotIn applies the NotIn predicate on the "ofd_url" field.
func OfdURLNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldOfdURL, vs...))
}

// OfdURLGT applies the GT predicate on the "ofd_url" field.
func OfdURLGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldOfdURL, v))
}

// OfdURLGTE applies the GTE predicate on the "ofd_url" field.
func OfdURLGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldOfdURL, v))
}

// OfdURLLT applies the LT predicate on the "ofd_url" field.
func OfdURLLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldOfdURL, v))
}

// OfdURLLTE applies the LTE predicate on the "ofd_url" field.
func OfdURLLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldOfdURL, v))
}

// OfdURLContains applies the Contains predicate on the "ofd_url" field.
func OfdURLContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldOfdURL, v))
}

// OfdURLHasPrefix applies the HasPrefix predicate on the "ofd_url" field.
func OfdURLHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldOfdURL, v))
}

// OfdURLHasSuffix applies the HasSuffix predicate on the "ofd_url" field.
func OfdURLHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldOfdURL, v))
}

// OfdURLEqualFold applies the EqualFold predicate on the "ofd_url" field.
func OfdURLEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldOfdURL, v))
}

// OfdURLContainsFold applies the ContainsFold predicate on the "ofd_url" field.
func OfdURLContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldOfdURL, v))
}

// XMLURLEQ applies the EQ predicate on the "xml_url" field.
func XMLURLEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldXMLURL, v))
}

// XMLURLNEQ applies the NEQ predicate on the "xml_url" field.
func XMLURLNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldXMLURL, v))
}

// XMLURLIn applies the In predicate on the "xml_url" field.
func XMLURLIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldXMLURL, vs...))
}

// XMLURLNotIn applies the NotIn predicate on the "xml_url" field.
func XMLURLNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldXMLURL, vs...))
}

// XMLURLGT applies the GT predicate on the "xml_url" field.
func XMLURLGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldXMLURL, v))
}

// XMLURLGTE applies the GTE predicate on the "xml_url" field.
func XMLURLGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldXMLURL, v))
}

// XMLURLLT applies the LT predicate on the "xml_url" field.
func XMLURLLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldXMLURL, v))
}

// XMLURLLTE applies the LTE predicate on the "xml_url" field.
func XMLURLLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldXMLURL, v))
}

// XMLURLContains applies the Contains predicate on the "xml_url" field.
func XMLURLContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldXMLURL, v))
}

// XMLURLHasPrefix applies the HasPrefix predicate on the "xml_url" field.
func XMLURLHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldXMLURL, v))
}

// XMLURLHasSuffix applies the HasSuffix predicate on the "xml_url" field.
func XMLURLHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldXMLURL, v))
}

// XMLURLEqualFold applies the EqualFold predicate on the "xml_url" field.
func XMLURLEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldXMLURL, v))
}

// XMLURLContainsFold applies the ContainsFold predicate on the "xml_url" field.
func XMLURLContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldXMLURL, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldIssuedAt, v))
}

// IssuedAtIsNil applies the IsNil predicate on the "issued_at" field.
func IssuedAtIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldIssuedAt))
}

// IssuedAtNotNil applies the NotNil predicate on the "issued_at" field.
func IssuedAtNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldIssuedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.NotPredicates(p))
}
